from collections import OrderedDict

INVENTORY_UPLOAD_WEBSTORE = OrderedDict([('operation', ''), ('sku', ''), ('item_name', ''), ('brand_name', ''),
    ('product_description', ''), ('bullet_point', ''), ('custom_page_title', ''), ('custom_meta_description', ''),
    ('variation_theme_id', ''), ('color_name', ''), ('size_name', ''), ('marketplaces', ''),
    ('suppressed_comparison_engine', ''), ('platinum_keywords', ''), ('generic_keywords', ''),
    ('our_price', ''), ('our_price_UOM', ''), ('offer_inventory_quantity', ''), ('discounted_price', ''),
    ('discounted_price_UOM', ''), ('discounted_price_start_date', ''), ('discounted_price_end_date', ''),
    ('RestockDate', ''), ('offering_start_date', ''), ('offering_end_date', ''), ('release_date', ''),
    ('max_order_quantity', ''), ('product_tax_code', ''), ('website_shipping_weight', ''),
    ('website_shipping_weight_UOM', ''), ('po_box_shipping_excluded', ''), ('offer_inventory_leadtime', ''),
    ('offering_condition', ''), ('product_type', ''), ('item_classification', ''), ('upc', ''), ('ean', ''),
    ('missing_keyset_reason', ''), ('country_of_origin', ''), ('can_be_giftwrapped', ''), ('can_be_giftmessaged', ''),
    ('fulfilled_by_amazon', ''), ('package_width', ''), ('package_width_UOM', ''), ('package_length', ''),
    ('package_length_UOM', ''), ('package_height', ''), ('package_height_UOM', ''), ('target_audience_keywords', ''),
    ('offering_condition_note', ''), ('specific_uses_keywords', ''), ('battery_type_lithium_ion', ''),
    ('number_of_lithium_metal_cells', ''), ('item_display_height', ''), ('item_display_height_UOM', ''),
    ('battery_type_product_specific', ''), ('number_of_pieces', ''), ('package_weight', ''), ('package_weight_UOM', ''),
    ('item_length', ''), ('item_length_UOM', ''), ('matte_style', ''), ('number_of_lithium_ion_cells', ''),
    ('item_package_quantity', ''), ('external_testing_certification', ''), ('part_number', ''), ('item_weight', ''),
    ('item_weight_UOM', ''), ('item_display_depth', ''), ('item_display_depth_UOM', ''), ('offering_subcondition', ''),
    ('lithium_battery_packaging', ''), ('is_discontinued_by_manufacturer', ''), ('thesaurus_attribute_keywords', ''),
    ('battery_type_cr123a', ''), ('battery_type_lithium_metal', ''), ('item_display_diameter', ''),
    ('item_display_diameter_UOM', ''), ('list_price', ''), ('list_price_UOM', ''), ('battery_type_aa', ''),
    ('pattern_name', ''), ('item_display_length', ''), ('item_display_length_UOM', ''), ('battery_type_9v', ''),
    ('volume_capacity_name', ''), ('battery_type_cr2', ''), ('battery_type_cr5', ''), ('are_batteries_included', ''),
    ('material_type', ''), ('battery_type_d', ''), ('color_map', ''), ('battery_type_c', ''), ('manufacturer', ''),
    ('battery_type_a', ''), ('hazmat_type', ''), ('thesaurus_subject_keywords', ''), ('model', ''), ('item_width', ''),
    ('item_width_UOM', ''), ('country_string', ''), ('occasion', ''), ('item_height', ''), ('item_height_UOM', ''),
    ('battery_type_aaa', ''), ('item_display_width', ''), ('item_display_width_UOM', ''), ('specification_met', ''),
    ('item_type_keyword', ''), ('style_name', ''), ('warranty_description', ''), ('cpsia_cautionary_statement', ''),
    ('item_display_weight', ''), ('item_display_weight_UOM', ''), ('telling_page_indicator', ''), ('battery_type_p76', ''),
    ('batteries_required', ''), ('usda_hardiness_zone', ''), ('sunset_climate_zone', ''), ('moisture_needs', ''),
    ('sunlight_exposure', ''), ('image_main', ''), ('image_pt01', ''), ('image_pt02', ''), ('image_pt03', ''),
    ('image_pt04', ''), ('image_pt05', ''), ('image_pt06', ''), ('image_pt07', ''), ('image_pt08', ''),
    ('image_swch', ''), ('custom_text_1', ''), ('custom_text_2', ''), ('custom_text_3', ''), ('custom_text_4', ''),
    ('custom_text_5', ''), ('custom_text_6', ''), ('custom_text_7', ''), ('custom_text_8', ''), ('custom_text_9', ''),
    ('custom_text_10', ''), ('custom_number_1', ''), ('custom_number_2', ''), ('custom_number_3', ''),
    ('custom_number_4', ''), ('custom_number_5', '')
])


PRICE_QUANTITY = OrderedDict([
    ('sku', ''),
    ('price', ''),
    ('minimum-seller-allowed-price', ''),
    ('maximum-seller-allowed-price', ''),
    ('quantity', ''),
    ('leadtime-to-ship', ''),
    ('fulfillment-channel', '')
])

INVENTORY_LOADER = OrderedDict([
    ('sku', ''),
    ('product-id', ''),
    ('product-id-type', ''),
    ('price', ''),
    ('minimum-seller-allowed-price', ''),
    ('maximum-seller-allowed-price', ''),
    ('item-condition', ''),
    ('quantity', ''),
    ('add-delete', ''),
    ('will-ship-internationally', ''),
    ('expedited-shipping', ''),
    ('standard-plus', ''),
    ('item-note', ''),
    ('fulfillment-center-id', ''),
    ('product-tax-code', ''),
    ('leadtime-to-ship', ''),
    ('merchant_shipping_group_name', '')
])

CATEGORY_INVENTORY_FILE = OrderedDict([
    ('item_sku', ''),
    ('external_product_id', ''),
    ('external_product_id_type', ''),
    ('item_name', ''),
    ('product_description', ''),
    ('feed_product_type', ''),
    ('brand_name', ''),
    ('manufacturer', ''),
    ('part_number', ''),
    ('item_type', ''),
    ('update_delete', ''),
    ('model', ''),
    ('standard_price', ''),
    ('condition_type', ''),
    ('condition_note', ''),
    ('quantity', ''),
    ('list_price', ''),
    ('map_price', ''),
    ('product_site_launch_date', ''),
    ('merchant_release_date', ''),
    ('restock_date', ''),
    ('fulfillment_latency', ''),
    ('product_tax_code', ''),
    ('sale_price', ''),
    ('sale_from_date', ''),
    ('sale_end_date', ''),
    ('item_package_quantity', ''),
    ('max_aggregate_ship_quantity', ''),
    ('offering_can_be_gift_messaged', ''),
    ('offering_can_be_giftwrapped', ''),
    ('is_discontinued_by_manufacturer', ''),
    ('missing_keyset_reason', ''),
    ('max_order_quantity', ''),
    ('number_of_items', ''),
    ('offering_start_date', ''),
    ('merchant_shipping_group_name', ''),
    ('website_shipping_weight', ''),
    ('website_shipping_weight_unit_of_measure', ''),
    ('item_display_length', ''),
    ('item_display_width', ''),
    ('item_display_height', ''),
    ('display_dimensions_unit_of_measure', ''),
    ('item_display_weight', ''),
    ('item_display_weight_unit_of_measure', ''),
    ('volume_capacity_name', ''),
    ('volume_capacity_name_unit_of_measure', ''),
    ('item_height', ''),
    ('item_length', ''),
    ('item_length_unit_of_measure', ''),
    ('item_weight', ''),
    ('item_weight_unit_of_measure', ''),
    ('item_width', ''),
    ('bullet_point1', ''),
    ('bullet_point2', ''),
    ('bullet_point3', ''),
    ('bullet_point4', ''),
    ('bullet_point5', ''),
    ('target_audience_base', ''),
    ('catalog_number', ''),
    ('specific_uses_keywords1', ''),
    ('specific_uses_keywords2', ''),
    ('specific_uses_keywords3', ''),
    ('specific_uses_keywords4', ''),
    ('specific_uses_keywords5', ''),
    ('target_audience_keywords1', ''),
    ('target_audience_keywords2', ''),
    ('target_audience_keywords3', ''),
    ('thesaurus_subject_keywords1', ''),
    ('thesaurus_subject_keywords2', ''),
    ('thesaurus_subject_keywords3', ''),
    ('generic_keywords', ''),
    ('main_image_url', ''),
    ('swatch_image_url', ''),
    ('other_image_url1', ''),
    ('other_image_url2', ''),
    ('other_image_url3', ''),
    ('fulfillment_center_id', ''),
    ('package_height', ''),
    ('package_width', ''),
    ('package_length', ''),
    ('package_dimensions_unit_of_measure', ''),
    ('package_length_unit_of_measure', ''),
    ('package_weight', ''),
    ('package_weight_unit_of_measure', ''),
    ('parent_child', ''),
    ('parent_sku', ''),
    ('relationship_type', ''),
    ('variation_theme', ''),
    ('prop_65', ''),
    ('cpsia_cautionary_statement', ''),
    ('cpsia_cautionary_description', ''),
    ('country_string', ''),
    ('country_of_origin', ''),
    ('legal_disclaimer_description', ''),
    ('safety_warning', ''),
    ('energy_efficiency_image_url', ''),
    ('lighting_facts_image_url', ''),
    ('breed_recommendation', ''),
    ('thesaurus_attribute_keywords', ''),
    ('special_features', ''),
    ('directions', ''),
    ('ingredients', ''),
    ('material_type', ''),
    ('closure_type', ''),
    ('compatible_devices', ''),
    ('age_range_description', ''),
    ('included_features', ''),
    ('specific_uses_for_product', ''),
    ('color_name', ''),
    ('color_map', ''),
    ('size_name', ''),
    ('size_map', ''),
    ('flavor_name', ''),
    ('maximum_weight_recommendation', ''),
    ('weight_recommendation_unit_of_measure', ''),
    ('external_testing_certification', ''),
    ('battery_type', ''),
    ('number_of_batteries', ''),
    ('lithium_battery_weight', ''),
    ('wattage', ''),
    ('pattern_name', ''),
    ('warranty_description', ''),
    ('fabric_type', ''),
    ('import_designation', ''),
    ('country_as_labeled', ''),
    ('fur_description', ''),
    ('paint_type', ''),
    ('number_of_sets', ''),
    ('occasion', ''),
    ('thread_count', ''),
    ('number_of_pieces', ''),
    ('item_shape', ''),
    ('scent_name', ''),
    ('included_components', ''),
    ('style_name', ''),
    ('usda_hardiness_zone1', ''),
    ('usda_hardiness_zone2', ''),
    ('specification_met', ''),
    ('mfg_minimum', ''),
    ('mfg_maximum', ''),
    ('material_composition', ''),
    ('fill_material_type', ''),
    ('light_source_type', ''),
    ('blade_edge_type', ''),
    ('blade_material_type', ''),
    ('theme', ''),
    ('power_source_type', ''),
    ('voltage', ''),
    ('engine_type', ''),
    ('hose_length', ''),
    ('hose_length_unit_of_measure', '')
])
