# All Pool Spa's categorical information for shopify, manufacturers, and distributors.
# This should be kept up to date with shopify.
from collections import OrderedDict

###############################SHOPIFY##################################
# Product Metafields
PRICING_PROFILES = {
    "vip": {"rules": {
                "markup":.3,
                "annual": 8000,
                'login': True
            },
            "price":""
    },
    "platinum": {"rules": {
                    "markup":.35,
                    "annual": 2000,
                    'login': True
                },
            "price":""
    },
    "gold": {"rules": {
                "markup":.4,
                "annual": 500,
                'login': True
            },
            "price":""
    },
    "silver": {"rules": {
                    "markup":.43,
                    "annual": 1,
                    'login': True
                },
            "price":""
    },
    "member": {"rules": {
                    "markup":.45,
                    "annual": 0,
                    'login': True
                },
            "price":""
    },
    "nonmember": {"rules": {
                    "markup":.5,
                    "annual": 0,
                    'login': False
                },
            "price":""
    },
    "amazon_prime": "",
    "amazon_lowest": "",
    "optimus_price": "",
    "scp_price": ""
}

EXTRA_PRODUCT_INFO = {
    "instructions": "",
    "warranty": "",
    "part_number": "",
    "oem": "",
    "original manufacturer": "",
    "parent": "",
    "fba": False,
    "amazon_features": [],
    "amazon_description": "",
    "amazon_img_url": "",
    "asin": "",
    "scp_sku": "",
    "optimus_sku": "",
}
SHOPIFY_PRODUCT_METAFIELDS = {
    "pricing" : PRICING_PROFILES,
    "info" : EXTRA_PRODUCT_INFO
}

# Customer Metafields
MEMBER_PROFILE = {
    "vip": False,
    "platinum": False,
    "gold": False,
    "silver": False,
    "member": False,
    "nonmember": False,
    "amazon": False,
}
SHOPIFY_CUSTOMER_METAFIELDS = {
    "member" : MEMBER_PROFILE
}


# Each Manufacturer gets a collection
MANUFACTURERS = [
    'Oreq',
    'Aquachek',
    'GAME',
    'Unicel',
    'Val-Pak',
    'U.S. SEAL',
    'Aladddin',
    'Waterway',
    'Zodiac',
    'Pentair',
    'Hayward',
    'A.O. Smith',
    'Afras',
    'Jandy',
    'Odyssey',
    'Polaris',
    'Raypak',
    'S.R. Smith',
    'Unicel',
    'US SEAL',
    'American Products',
    'Pac-Fab',
    'PacFab',
    'Pac Fab',
    'Harmsco',
    'Martin',
    'Anthony',
    'Paragon',
    'Purex',
    'Swimquip',
    'Sta-Rite',
    'Marlin',
    'Marquis',
    'Fountain Valley Spa',
    'Baker',
    'Waterco',
    'Atlantic',
    'Jacuzzi',
    'Aquatemp',
    'Muskin',
    'Rainbow',
    'Sundance',
    'American',
    'Premier',

]

# All the collections for the shopify allpoolspa.com
COLLECTIONS = [
    'Popular in Filters',
    'Popular in Pumps',
    'Popular in O-Rings',
    'Popular in Baskets',
    'On Sale',
    'O-Rings & Gaskets',
    'Maintenance',
    'White Goods',
    'Valves',
    'Pool Cleaners',
    'Skimmers',
    'Filters',
    'Pumps',
    'Motors',
    'Best Sellers',
    'Spa',
    'Floats & Toys',
    'Accessories',
    'Equipment',
    'Covers',
    'Automation',
    'Sanitization',
    'Lighting',
    'Heaters',
    'Heat Pumps',
    'Air Blowers',
    MANUFACTURERS
]

# All The Types (keys) and Tags (values) for shopify allpoolspa.com
POOL_TYPES = ['pool', 'spa', 'commercial', 'residential']
COMMON = [
    'part', 'accessory', 'miscellaneous', 'maintenance',
    'accessories','unit', 'wholegood', 'equipment', 'o-ring',
    'gasket', 'lid', 'cover', 'kit',

]
TYPES_N_TAGS = {
    'Filters' : [
        'sand',
        'de',
        'cartridge',
        'valve',
        'separation tank',
        'replacement',
        'system',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Pumps' : [
        'variable',
        'multiple speed',
        'two speed',
        'single speed',
        'motor',
        'pump seal',
        'capacitor',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Motors' : [
        'pump seal',
        'bearing',
        'capacitor',
        'variable',
        'multiple speed',
        'two speed',
        'single speed',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Heaters' : [
        'gas',
        'propane',
        'electric',
        'heat exchanger',
        'header',
        'union',
        'control',
        'panel',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Heat Pumps' : [
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Air Blowers' : [
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'White Goods' : [
        'pressure',
        'gauge',
        'skimmer',
        'cover',
        'weir',
        'drain',
        'main drain',
        'grate',
        'basket',
        'pvc',
        'plumbing',
        'skimmer',
        'cover',
        'weir',
        'valve',
        'jet',
        'junction box',
        'flow fitting',
        'strainer',
        'anti-entrapment',
        'return',
        'inlet',
        'electrical',
        'electric',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Skimmers' : [
        'skimmer',
        'cover',
        'weir',
        'basket',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Lighting' : [
        'fiber optic',
        'led',
        'floating',
        'fountain',
        'halogen',
        'incandescent',
        'landscape',
        'light',
        'lighting',
        'auto controller',
        'niches',
        'bulb',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Automation' : [
        'control',
        'controller',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'O-Rings & Gaskets' : [
        'pump',
        'skimmer',
        'filter',
        'heater',
        'lighting',
        'valve',
        'lubricant',
        'accessory',
        'miscellaneous',
        'heat pump',
        'cleaner',
        'automation',
        'sanitization',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Sanitization' : [
        'salt system',
        'salt',
        'ozone',
        'UV',
        'chlorine'
        'feeder',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Maintenance' : [
        'test kit',
        'leaf rake',
        'vacuum',
        'brush',
        'thermometer',
        'basket',
        'miscellaneous',
        'reagent',
        'test strip',
        'testing',
        'vacuum head',
        'hose',
        'saddle clamp',
        'test plug',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Deck Accessories' : [
        'rail',
        'water feature',
        'slide',
        'ladder',
        'diving',
        'lifeguard',
        'game',
        'escutcheon',
        'lift',
        'jump stand',
        'platform',
        'chair',
        'reels',
        'pool access',
        'stanchions',
        'board',
        'anchor',
        'waterfall',
        'paint',
        'spray paint',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Covers' : [
        'winter',
        'solar',
        'heater',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Accessories': [
        'float',
        'toy',
        'thermometers',
        'safety',
        'sign',
        'water feature',
        'maintenance',
        'cover',
        'fountain',
        'paint',
        'spray paint',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Cleaners': [
        'suction',
        'pressure',
        'robotic',
        'manual',
        'pump',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'O-Rings & Gaskets' : [
        'oring',
        'gasket',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Valves' : [
        'valve',
        'backwash',
        'filter',
        'multiport',
        'ball',
        'check',
        'diverter',
        'filter control valve',
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Miscellaneous' : [
        POOL_TYPES,
        COMMON,
        MANUFACTURERS
    ],
    'Floats & Toys' : [
        'float',
        'game',
        'basketball',
        'volleyball',
        'inflatable',
        'chair',
    ]
}

# All the menus/linklists for the shopify allpoolspa.com navigation
MENUS = {
    "Main Menu": [
        'Manufacturers',
        'Parts',
        'Equipment',
        'Maintenance',
        'Accessories',
        'Spa',
        'Floats & Toys',
    ],
    'Accessories': [
        'Floating Lights'
        'Floats & Toys',
        'Thermometers',
        'Safety',
        'Signs',
        'Water Features',
        'Maintenance',
        'Covers',
    ],
    'Cleaners': [
        'All Pool Cleaners',
        'Suction Cleaners',
        'Robotic Cleaners',
        'Pressure Cleaners',
        'Manual Vacuums',
        'Cleaner Parts',
        'Cleaner Accessories',
    ],
    'Covers': [
        'All Covers',
        'Winter Covers',
        'Solar Covers',
    ],
    'Deck Equipment': [
        'Rails',
        'Water Features',
        'Slides',
        'Pool Access Equipment',
        'Ladders',
        'Diving',
        'Pool Access',
        'Lifeguard',
        'Games',
    ],
    'Equipment': [
        'Filters',
        'Pumps',
        'Heaters',
        'Pool Cleaners',
        'Sanitization',
        'Automation',
        'Skimmers',
        'Lighting',
        'Air Blowers',
    ],
    'Spa': [
        'Filters',
        'Heaters',
        'Pumps',
        'Baskets',
        'Jets',
        'Accessories',
    ],
    'Filters': [
        'All Filters',
        'Sand Filters',
        'DE Filters',
        'Cartridge Filters',
        'Filter Parts',
        'Filter Accessories',
    ],
    'Lighting':[
        'All Lights',
        'Pool Lights',
        'Spa Lights',
        'LED Lights',
        'Fiber Optic Lights',
        'Floating Lights',
        'Fountain Lights',
        'Halogen Lights',
        'Incandescent Lights',
        'Landscape Lights',
        'Light Parts',
        'Light Accessories',
    ],
    'Pumps': [
        'All Pumps',
        'Single Speed Pumps',
        'Multiple Speed Pumps',
        'Variable Speed Pumps',
        'Motors',
        'Pump Parts',
        'Pump Accessories',
    ],
    'About All Pool Spa': [
        'About Us',
        'FAQs',
        'Refund & Exchange Policies',
        'Contact Us',
        'Manufacturer Rebates',
        'Privacy & Security Policies',
        'Terms and Conditions',
        'Vendor Relations',
    ],
    'Heaters': [
        'All Heaters'
        'Gas Heaters'
        'Propane Heater'
        'Electric Heaters'
        'Heat Pumps'
        'Heater Parts'
        'Heater Accessories'
    ],
    'White Goods': [
        'skimmers',
        'skimmer covers',
        'skimmer baskets',
        'skimmer weirs'
        'main drains',
        'deck drains',
        'valves',
        'plumbing',
        'jets'
    ],
    'Maintenance' : [
        'Test Kits',
        'Test Strips',
        'Leaf Rakes',
        'Vacuums',
        'Brushes',
        'Thermometers',
        'Baskets',
    ],
    'O-Rings & Gaskets': [
        'Filter O-Rings/Gaskets',
        'Pump O-Rings/Gaskets',
        'Heater O-Rings/Gaskets',
        'Valve O-Rings/Gaskets',
        'Pool Cleaner O-Rings/Gaskets',
        'White Good O-Rings/Gaskets',
        'Light O-Rings/Gaskets',
    ],
    'Parts': [
        'O-Rings & Gaskets',
        'Filter Parts',
        'Pump Parts',
        'Heater Parts',
        'Pool Cleaner Parts',
        'Lighting Parts',
        'Valve Parts',
        'Automation Parts',
        'Skimmer Parts',
        'Plumbing',
        'White Goods',
    ],
    'Pumps': [
        'All Pumps',
        'Single Speed Pumps',
        'Multiple Speed Pumps',
        'Variable Speed Pumps',
        'Motors',
        'Pump Parts',
        'Pump Accessories',
    ],
    'Sanitization' : [
        'All Sanitization',
        'Chlorine',
        'Salt Systems',
        'Ozone',
        'UV',
        'Tablet Feeders',
        'Sanitizatizer Parts    ',
    ],
    'Skimmers': [
        'All Skimmers',
        'Skimmer Units',
        'Skimmer Covers',
        'Skimmer Baskets',
        'Skimmer Weirs',
    ],
}
########################END SHOPIFY#####################################


# Manufacturers and distributor categories. Use _CLEANCATS
_CATEGORIES = {
    # Optimus
    "Cleaners, Robotic" : "Cleaners, Robotic",
    "Chemical Feeders" : "Chemical Feeders, Sanitization",
    "Cleaners, Suction" : "Cleaners, Suction",
    "DE Filter Modules" : "DE Filter Modules, Filters",
    "Deck and Gutter Drains" : "Deck and Gutter Drains, White Goods",
    "Filter Cartridges" : "Filter Cartridges, Filters",
    "Filters, Cartridge Type" : "Filters, Cartridge Type",
    "Filters, DE, Grid Type" : "Filters, DE, Grid Type",
    "Filters, DE, Module Type" : "Filters, DE, Module Type",
    "Filters, DE, Perflex Type" : "Filters, DE, Perflex Type",
    "Heat Pumps" : "Heat Pumps",
    "Gas Heaters" : "Gas Heaters, Heaters",
    "Filters, Sand, Top Mount" : "Filters, Sand, Top Mount, Valves",
    "Filters, Sand, Side Mount" : "Filters, Sand, Side Mount, Valves",
    "Filter Valves, Top Mount" : "Filter Valves, Top Mount, Valves",
    "Filter Valves, Side Mount" : "Filter Valves, Side Mount, Valves",
    "Filter Valves, Push Pull" : "Filter Valves, Push Pull, Valves",
    "Inlet Fittings" : "Inlet Fittings, White Goods",
    "Light Niches" : "Light Niches, Lighting",
    "Lights, AG Thru Wall" : "Lights, AG Thru Wall, Lighting",
    "Lights, Niche type" : "Lights, Niche type, Lighting",
    "Main Drains" : "Main Drains, White Goods",
    "PH and ORP Controllers" : "PH and ORP Controllers, Automation",
    "Plumbing Unions" : "Plumbing Unions, White Goods",
    "Plumbing Valves" : "Plumbing Valves, White Goods",
    "Pumps" : "Pumps",
    "Seperation Tanks" : "Seperation Tanks, Filters",
    "Skimmers" : "Skimmers",
    "Vacuum Heads" : "Vacuum Heads, Maintenance",
    "Vacuum Release Systems" : "Vacuum Release Systems, White Goods",
    "Valve Actuators" : "Valve Actuators, Automation",
    "Slides": "Slides, Deck Accessories",
    "Diving Boards": "Diving Boards, Deck Accessories",
    "Gas Heaters": "Gas Heaters, Heaters",
    "Fillspouts": "Fillspouts, Deck Accessories",
    "Pump Motors": "Pumps, Motor",
    # SCP
    "Main Drains, Commercial" : "White Goods",
    "Heat Pumps" : "Heat Pumps",
    "Filters, DE" : "Filters, DE",
    "Filter Control Valves" : "Filter Control Valves, Valves",
    "Parts, Whitegoods Flow Fittings, Commercail" : "Parts, White Goods, Flow Fittings, Commercail",
    "Parts, Plumbing" : "Parts, Plumbing, White Goods",
    "Motors, Residential" : "Motors, Residential, Pumps",
    "Parts, Lights Auto Controllers" : "Parts, Lights Auto Controllers, Lighting",
    "Miscellaneous, Maintenance" : "Miscellaneous, Maintenance",
    "Parts, Feeders Chlorinators Sanitizers" : "Sanitization, Parts, Feeders Chlorinators Sanitizers",
    "Heaters, Electric" : "Heaters, Electric",
    "Controls" : "Controls, Automation",
    "Strainers, Commercial" : "Strainers, Commercial, White Goods",
    "Anti-Entrapment Main Drains, Commercial" : "Anti-Entrapment Main Drains, Commercial, White Goods",
    "Service Repair Install" : "Service Repair Install, Maintenance",
    "Chem Feeders" : "Chem Feeders, Sanitization",
    "Miscellaneous, Deck Equipment" : "Miscellaneous, Deck Accessories",
    "Filter Systems, DE" : "Filter Systems, DE, Filters",
    "Motors, Comm" : "Motors, Comm, Pumps",
    "Miscellaneous, Lights Auto Controllers" : "Miscellaneous, Lights Auto Controllers, Lighting",
    "Pool Saftey Devices" : "Pool Saftey Devices, Safety, Accessories",
    "Cleaners, Electric Robotic" : "Cleaners, Robotic",
    "Plumbing Valves Unions" : "Plumbing Valves Unions, Valves",
    "Miscellaneous, Whitegoods Flow Fittings, Comm" : "Miscellaneous, White Goods, Flow Fittings, Comm",
    "Filters, Cartridge, Commercial" : "Filters, Cartridge, Commercial",
    "Junction Box" : "Junction Box, White Goods",
    "Covers, Winter" : "Covers, Winter",
    "Parts, Automatic Cleaners" : "Parts, Automatic Cleaners, Cleaners",
    "Main Drains" : "Main Drains, White Goods",
    "Spa Accessories Hardware" : "Spa Accessories Hardware, Accessories",
    "Test Plugs" : "Test Plugs, White Goods",
    "Parts, Heaters" : "Parts, Heaters",
    "Lubes" : "Lubes, Maintenance",
    "Parts, Filter" : "Parts, Filters",
    "Filters, Sand, Commercial" : "Filters, Sand, Commercial",
    "Designer Fountains" : "Designer Fountains, Accessories",
    "Miscellaneous, Plumbing" : "Miscellaneous, Plumbing, White Goods",
    "Deck Drains Deck Joints Deck Grates" : "Deck Drains Deck Joints Deck Grates, White Goods",
    "Miscellaneous, White Goods Flow Fittings" : "Miscellaneous, White Goods, Flow Fittings",
    "Miscellaneous, White Goods Flow Fittings, Comm" : "Miscellaneous, White Goods, Flow Fittings, Commercial",
    "Return Inlet Fittings" : "Return Inlet Fittings, White Goods",
    "Heater Venting" : "Heater Venting, Heaters",
    "Parts, Pumps" : "Parts, Pumps",
    "Niches" : "Niches, Lighting",
    "Replacement, Cartridges" : "Replacement, Cartridges, Filters, Cartridge",
    "Pool Spa Lights" : "Pool Spa Lights, Lighting",
    "Heaters" : "Heaters",
    "Parts, Whitegoods Flow Fittings" : "Parts, White Goods, Flow Fittings",
    "Separation Tanks" : "Separation Tank, Filters",
    "Alarms, Pool Entry" : "Alarm, Pool Entry, Safety, Accessories",
    "Replacement, DE Grids" : "Replacement, DE, Grid, Filters",
    "Pumps, Commercial" : "Pumps, Commercial",
    "Replacement Bulbs" : "Replacement Bulb, bulb, Lighting",
    "Skimmers" : "Skimmers",
    "Test Meters Labs" : "Test Meters Labs, Maintenance, testing",
    "Parts, Miscellaneous Deck Equipment" : "Parts, Miscellaneous, Deck Accessories",
    "Cleaners, Suction" : "Cleaners, Suction",
    "Parts, Pumps, Commercial" : "Parts, Pumps, Commercial",
    "Pumps, Residential" : "Pumps, Residential",
    "PVC Fittings" : "PVC Fittings, White Goods",
    "Spa, Jets" : "Spa, Jets, White Goods",
    "Chem Feeders, Commercial" : "Chem Feeders, Commercial, Sanitization",
    "Filters, Sand" : "Filters, Sand",
    "Filters, Cartridge" : "Filters, Cartridge",
    "Chlorinators Floating Dispensers" : "Chlorinators Floating Dispensers, Sanitization",
    "Salt Generators, Commercial" : "Salt Generators, Commercial, Sanitization",
    "Plumbing Valves Unions, Commercial" : "Plumbing Valves Unions, Commercial, Valves",
    "Parts, Spa" : "Parts, Spa, White Goods",
    "Miscellaneous, Feeders Chlorinators Santizers" : "Sanitization, Feeders Chlorinators Santizers",
    "Fiber Optics" : "Fiber Optics, Lighting",
    "O-Rings" : "Rings, O-Rings & Gaskets",
    "Filter Systems, Sand" : "Filter Systems, Sand, Filters",
    "Vacuums, All" : "Vacuums, All, Maintenance",
    "Tools, Hand" : "Tools, Hand, Maintenance",
    "Filter Systems, Cartridge" : "Filter Systems, Cartridge, Filters",
    "Cleaners, Pressure" : "Cleaners, Pressure",
    "Salt Generators" : "Salt Generators, Sanitization",
    "Test Kits Reagents" : "Test Kits, Reagents, Maintenance",
    "Cleaners, Commercial" : "Cleaners, Commercial",
    "Filter Control Valves, Commercial" : "Filter Control Valves, Commercial, Valves",
    "Parts, Maintenance" : "Parts, Maintenance",
    "Heaters Gas, Commercial" : "Heaters Gas, Commercial, Heaters",
    "Parts, Filter Accessories" : "Parts, Filter Accessories, Filters",
    # SCP product lines
    "AUTOMATIC CLEANERS" : "Cleaners",
    "HEATERS" : "Heaters",
    "PLUMBING, ALL" : "White Goods",
    "WHITEGOODS FLOW FITTINGS" : "White Goods",
    "POOL SERVICE" : "Maintenance",
    "FEEDERS CHLORINATORS SANTIZERS" : "Sanitization",
    "COVERS" : "Covers",
    "ELECTRICAL" : "Electrical",
    "MAINTENANCE EQUIP" : "Maintenance",
    "DECK EQUIPMENT" : "Deck Accessories",
    "DECK CONSTRUCTION" : "Deck Accessories",
    "PUMPS" : "Pumps",
    "FILTERS" : "Filters",
    "POOL SPA LIGHTING, AUTO CONTROLLERS" : "Lighting, Auto Controllers",
    "WATER FEATURES" : "Accessories, water features",
    "SAFETY" : "Safety",
    "FILTER ACCESSORIES" : "Filters, Accessories",
    "TOOLS" : "Maintenance, Tool",
    "SPA MISC" : "White Goods, Spa",
    "TESTING EQUIPMENT" : "Maintenance, testing",
    #
    "Vacuum Hose Parts": "Maintenance, vacuum, part",
    "Miscellaneous, Filter": "Filters, part, accessory",
    "Service Repair Install Parts": "Maintenance",
    "Slides": "Slides, Deck Accessories",
    "Starting Platforms": "Starting Platforms, Deck Accessories",
    "Transfer Rails": "Transfer Rails, Deck Accessories",
    "Games": "Games, Deck Accessories",
    "Lifeguard Chairs": "Lifeguard Chairs, Deck Accessories",
    "Rails": "Rails, Deck Accessories",
    "Ladders": "Ladders, Deck Accessories",
    "Therapeutic Bars": "Therapeutic Bars, Deck Accessories",
    "Parts": "Parts, Deck Accessories",
    "Lighting": "Lighting",
    "Storage Reels": "Storage Reels, Deck Accessories",
    "Pool Access Equipment": "Pool Access Equipment, Deck Accessories",
    "Water Features": "Water Features, Deck Accessories",
    "Diving": "Diving, Deck Accessories",
    "Stanchions": "Stanchions, Deck Accessories",
    "Starting Platform": "Starting Platform, Deck Accessories",
    "Ladders": "Ladders, Deck Accessories",
    "Jump Stand": "Jump Stand, Deck Accessories",
    "Control Systems": "Control Systems, Automation",
    "Accessories": "Accessories",
    "Escutcheons": "Escutcheons, Deck Accessories",
    "Bulk Fiber": "Bulk Fiber, Lighting",
    "Parts": "Parts, Deck Accessories",
    "Treads": "Treads, Deck Accessories",
    "Rubber Bumper": "Rubber Bumper, Deck Accessories",
    "Escutcheon": "Escutcheon, Deck Accessories",
    "Pool Lift": "Pool Lift, Deck Accessories",
    "Illuminators": "Illuminators, Lighting",
    "Anchors": "Anchors, Deck Accessories",
    "Aquatic Chair": "Aquatic Chair, Deck Accessories",
    "Boards": "Boards, Deck Accessories",
    "O-Rings": "O-Rings & Gaskets",
    "Fittings, Brass": "Fittings - Brass, White Goods, PVC",
    "Tools, Hand": "Tools, Hand, Maintenance",
    "Portable Vacuum Systems Liner Vac": "Portable Vacuum Systems Liner Vac, Maintenance",
    "Test Plugs": "Test Plugs, White Goods",
    "Go-Kits": "Go-Kits, O-Rings & Gaskets, kit",
    "Spa Accessories Hardware": "Spa Accessories Hardware, Accessories",
    "Tool Accessories": "Tool Accessories, Maintenance",
    "Parts, Filter": "Parts, Filter, Filters",
    "Lubes": "Lubes, Accessories",
    "Miscellaneous, Plumbing": "Miscellaneous, Plumbing, White Goods",
    "Miscellaneous, White Goods Flow Fittings": "Miscellaneous, White Goods, Flow Fittings",
    "Return Inlet Fittings": "Return Inlet Fittings, White Goods",
    "Nuts Bolts Screws": "Nuts Bolts Screws, Maintenance",
    "Gaskets": "Gaskets, O-Rings & Gaskets",
    "Timers Switches": "Timers Switches, Maintenance",
    "Parts, Filter Accessories": "Parts, Filters, Accessories",
    "Parts, Heaters, Commercial": "Parts, Heaters, Commercial",
    "Electric Spa Heaters, Standalone": "Heaters, Electric, Spa, Equipment",
    "Spray Marking Paint": "Spray Paint, Accessories, Part",
    "Pentair Filter Parts": "Filters, part",
    "Jandy Filter Parts": "Filters, part",
    "Purex Filter Parts": "Filters, part",
    "Ortega Valve Parts": "Valves, part, ortega",
    "White Goods": "White Goods",
    "Motors & Pumps": "Pumps, motor",
    "Filters": "Filters",
    "Spa Accessories Comp Products": "Spa, Accessories",
    "Pipe, Flex": "PVC, White Goods, Plumbing",
    "Pumps, Spa": "Pumps, spa",
    "Miscellaneous, Spa": "Spa, Accessories, part",
    "Spa Blowers": "Air Blowers, spa, wholegood",
    "Air Blowers": "Air Blowers, spa, wholegood",
    "Spa Controls Components": 'Spa, Automation',
    "Lights, Thru Wall Spa": "Lighting, wholegood, spa",
    "Plumbing Fittings": "White Goods, Plumbing",
    "Miscellaneous, Water Features": "Deck Accessories",
    "Pressure Vacuum Gauges": "Accessories, gauge",
    "Miscellaneous, Electrical": "White Goods, electrical",
    "Waterfall": "Water Features, Deck Accessories",
    "Check Valves": "Valves, check, check valve",
    "Valves": "Valves",
    "Plumbing": "Plumbing, White Goods, part",
    "Sanitization":"Sanitization",
    "Cleaners":"Cleaners",
    "Automation":"Automation",
    "Deck Laminar Jets":"Deck Accessories, water feature, jet",
    "LED":"Lighting, LED",
    "Parts, Water Features":"White Goods, water feature, part",
    "Designer Sconces":"Accessories, sconce",
    "Non, Chemical Sanitizer":"Sanitization",
    "Chemicals Sanitizer":"Sanitizer, Chemicals",
    "Miscellaneous, Spa Chemical":"Chemicals, Spa",
    "Auto Fills":"White Goods, autofill, auto fill",
    "Cleaners, Infloor":"Cleaners, infloor",
    "Misc, Feeders Chlorinators Sanitizers, Comm":"Sanitization, chlorinator, feeder",
    "Heat Pumps, Comm":"Heat Pumps, commercial, unit",
    "Test Strips":"Maintenance, testing, water testing, test strip",
    "Deck Jets":"Deck Accessories, jet",
    "Solar Reels":"Accessories, cover, solar reel",
    "Salt Chlorine Generators":"Sanitization, salt",
    "Pool Controls":"Automation, control",
    "Leaf Vacs":"Maintenance, leaf vac, vacuum",
    "Chemical Feeders, Watermatic":"Sanitization, feeder, chemical feeder",
    "Cleaners, Pop Up":"Cleaners, infloor",
    "In Pool Fountains":"Accessories, fountain, water feature",
    "Leaf Trappers":"Cleaners, accessory, leaf trap",
    # Pentair Optimus
    "Compool / Pentair Pool Control System Circuit Boards": "Pool Controls, Automation",
    "Compool / Pentair Pool Control System Parts": "Pool Controls, Automation",
    "Compool / Pentair Pool Control System Spa Side Remotes": "Pool Controls, Automation",
    "Compool / Pentair Pool Control System Valve Actuators": "Valve Actuators, Automation",
    "Hayward and Pentair Deck & Gutter Drains": "Deck and Gutter Drains, White Goods",
    "Hayward and Pentair Safety Vac Locks": "Cleaners, Accessory",
    "Leaf Vacs, Various Models": "Leaf Vacs, Vacuum, Maintenance",
    "Letro / Pentair Booster Pump, Older version": "Cleaners, Pressure, Pump",
    "Miscellaneous Vacuum Head Parts": "Vacuum Heads, Maintenance",
    "Ortega /Pentair T-Style Diverter Valves": "Plumbing Valves, Valves",
    "Pentair - A.O. Smith Commercial Pump Motors": "Pump Motors, Pumps",
    "Pentair / American Complete Amerlite Pool Lights": "Lights, Lighting, Niche type",
    "Pentair / American Complete Aqualight Spa and Pool Lights": "Lights, Lighting, Niche type",
    "Pentair / American Complete Aqualumin III Pool Lights": "Lights, Lighting, Niche type",
    "Pentair / American Complete Aqualuminator Above Ground Pool Light and Return": "Lights, Lighting, Combo AG",
    "Pentair / American Complete Full Size Stainless Steel Niches": "Light Niches, Lighting",
    "Pentair / American Complete Small Stainless Steel Niches": "Light Niches, Lighting",
    "Pentair / American Complete Spa Brite Spa Lights": "Lights, Lighting, Niche type",
    "Pentair / American Complete Spectrum Amerlite Pool Lights": "Lights, Lighting, Niche type",
    "Pentair / American Complete Spectrum Aqualight Pool and Spa Lights": "Lights, Lighting, Niche type",
    "Pentair / American Products 5 and 8 Position Top Mount": "Filter Valves, Valves, Top Mount",
    "Pentair / American Products 6 Position Top Mount": "Filter Valves, Valves, Top Mount",
    "Pentair / American Products Americana Pump": "Pumps",
    "Pentair / American Products Aqualuminator,Quasar, Quasar 500": "Lights, Lighting, Combo AG",
    "Pentair / American Products Commander Cartridge": "Filters, Cartridge Type",
    "Pentair / American Products Diverter Valve Parts": "Plumbing Valves, Valves",
    "Pentair / American Products Eagle Pump": "Pumps",
    "Pentair / American Products Eclipse & Meteor Top Mount": "Filters, Sand, Top Mount",
    "Pentair / American Products Eclipse Side Mount": "Filters, Sand, Side Mount",
    "Pentair / American Products In Ground Admiral Skimmers": "Skimmers",
    "Pentair / American Products Maxim Pump": "Pumps",
    "Pentair / American Products Predator Cartridge": "Filters, Cartridge Type",
    "Pentair / American Products Push Pull Valve": "Filter Valves, Valves, Push Pull",
    "Pentair / American Products Quantum, CM Series, Cartridge": "Filters, Cartridge Type",
    "Pentair / American Products Quantum, RPM Cartridge": "Filters, Cartridge Type",
    "Pentair / American Products Quantum, Stainless Steel Cartridge": "Filters, Cartridge Type",
    "Pentair / American Products Sandpiper Filter Side Mount": "Filters, Sand, Side Mount",
    "Pentair / American Products Separation Tanks": "Seperation Tanks, Filters",
    "Pentair / American Products Side Mount 1-1/2\"": "Filter Valves, Valves, Side Mount",
    "Pentair / American Products Side Mount 2\"": "Filter Valves, Valves, Side Mount",
    "Pentair / American Products Small Skimmers, FAS 100": "Skimmers",
    "Pentair / American Products Titan, CM DE Filter": "Filters, DE, Grid Type",
    "Pentair / American Products Titan, RPM DE Filter": "Filters, DE, Grid Type",
    "Pentair / American Products Titan, SS DE Filter": "Filters, DE, Grid Type",
    "Pentair / American Products Ultra Flo Pump": "Pumps",
    "Pentair / Compool Complete Diverter Valves": "Plumbing Valves, Valves",
    "Pentair / Compool Diverter Valve Parts": "Plumbing Valves, Valves",
    "Pentair / Hydrel Complete Halogen Spa and Pool Lights": "Lights, Lighting, Niche type",
    "Pentair / Hydrel Sunlite Niche": "Light Niches, Lighting",
    "Pentair / Kreepy E-Z Vac & Kadet Accessories": "Cleaners, Suction",
    "Pentair / Kreepy Krauly 1993 and Prior Accessories": "Cleaners, Suction",
    "Pentair / Kreepy Krauly 1994 - 1999": "Cleaners, Suction",
    "Pentair / Kreepy Krauly 1994 and Prior": "Cleaners, Suction",
    "Pentair / Kreepy Krauly 1994 to Current Accessories": "Cleaners, Suction",
    "Pentair / Kreepy Krauly 2000 to Current": "Cleaners, Suction",
    "Pentair / Kreepy Krauly E-Z Vac": "Cleaners, Suction",
    "Pentair / Kreepy Krauly Kadet": "Cleaners, Suction",
    "Pentair / Kreepy Krauly Legend, Model LL505G": "Cleaners, Pressure",
    "Pentair / Kreepy Krauly Thruster": "Cleaners, Suction",
    "Pentair / Letro - A.O. Smith / Magnetek Cleaner Pump Motors": "Pump Motors, Pumps",
    "Pentair / Letro - Emerson Cleaner Pump Replacement Motors": "Pump Motors, Pumps",
    "Pentair / Letro Autofills, T40 & T40FN": "Autofills, White Goods",
    "Pentair / Letro Inline Thermometers": "Thermometers, Accessories",
    "Pentair / Pac Fab 2\" Slide Valve": "Filter Valves, Valves, Push Pull",
    "Pentair / Pac Fab Hi-Flow 2\"": "Filter Valves, Valves, Side Mount",
    "Pentair / Pac Fab Hydropump, 590 & 700 Series": "Pumps",
    "Pentair / Pac Fab In Ground Bermuda Skimmers": "Skimmers",
    "Pentair / Pac Fab In Ground Skim-Clean Skimmers": "Skimmers",
    "Pentair / Pac Fab Pinnacle Pump": "Pumps",
    "Pentair / Pac Fab Top Mount Valve 1-1/2\"": "Filter Valves, Valves, Top Mount",
    "Pentair / Pac Fac Dynamo Pump": "Pumps",
    "Pentair / Pac-Fab Hatteras Pool Niche": "Light Niches, Lighting",
    "Pentair / Praher Complete Valves": "Filter Valves, Valves, Side Mount",
    "Pentair / Praher Valves, 1-1/2\"": "Filter Valves, Valves, Top Mount",
    "Pentair / Praher Valves, 2\" ": "Filter Valves, Valves, Top Mount",
    "Pentair / Purex 2000 Series Backwash Valve": "Filter Valves, Valves, Bottom Mount",
    "Pentair / Purex C Series Commericial Pump": "Pumps",
    "Pentair / Purex CFW Cartridge, CFW-120, 180, 315, 405": "Filters, Cartridge Type",
    "Pentair / Purex CMF Cartridge, CFM-120, 180, 315": "Filters, Cartridge Type",
    "Pentair / Purex Quietflo & Aquatron": "Pumps",
    "Pentair / Purex SM, SMBW 4000 Series DE": "Filters, DE, Grid Type",
    "Pentair / Purex SMBW 1000 & 2000 Series DE, Stainless": "Filters, DE, Grid Type",
    "Pentair / Purex Stainless DE Separation Tank, SEP-48, 72, 96, 144": "Seperation Tanks, Filters",
    "Pentair / Purex Tahitian Top Mount, HR-21, 25, 31": "Filters, Sand, Top Mount",
    "Pentair / Purex Tahitian Valve": "Filter Valves, Valves, Top Mount",
    "Pentair / Purex Tropic Isle Heaters, 120 - 300": "Gas Heaters, Heaters",
    "Pentair / Purex Whisperflo Pump, Models WF & WFE": "Pumps",
    "Pentair / Rainbow Bromine Feeder": "Chemical Feeders, Sanitization",
    "Pentair / Rainbow Complete DSF Series Skim Filters": "Skimmers",
    "Pentair / Rainbow Complete High Capacity Feeders": "Chemical Feeders, Sanitization",
    "Pentair / Rainbow Complete In Line Feeders": "Chemical Feeders, Sanitization",
    "Pentair / Rainbow Complete Off Line Feeders": "Chemical Feeders, Sanitization",
    "Pentair / Rainbow DSF Skim Filter": "Skimmers",
    "Pentair / Rainbow Flex Vac Heads": "Vacuum Heads, Maintenance",
    "Pentair / Rainbow Floating Feeders": "Floating Chemical Feeders, Sanitization",
    "Pentair / Rainbow Free Standing Feeders": "Chemical Feeders, Sanitization",
    "Pentair / Rainbow In Line Feeders": "Chemical Feeders, Sanitization",
    "Pentair / Rainbow Leaf Trap Model 180": "Leaf Traps, Accessories, Cleaner",
    "Pentair / Rainbow Leaf Trap, Model 179, 179C": "Leaf Traps, Accessories, Cleaner",
    "Pentair / Rainbow Leaf Trap, Model 186": "Leaf Traps, Accessories, Cleaner",
    "Pentair / Rainbow Pro Vac": "Vacuum Heads, Maintenance",
    "Pentair / Rainbow Super Pro Vac, Model 241": "Vacuum Heads, Maintenance",
    "Pentair / Rainbow Swivel Wheel Flex Vac": "Vacuum Heads, Maintenance",
    "Pentair / Rainbow Vinyl Vac": "Vacuum Heads, Maintenance",
    "Pentair / Sta-Rite / Swimquip Inlet Fitting": "Inlet Fittings, White Goods",
    "Pentair / Sta-Rite 4\" Suction Trap, Package 142 & 175": "Pumps",
    "Pentair / Sta-Rite ABG Series Pump": "Pumps",
    "Pentair / Sta-Rite Above Ground Skimmers, 09655-6403, 09655-7403": "Skimmers",
    "Pentair / Sta-Rite Calypso, Model GW7000": "Cleaners, Suction",
    "Pentair / Sta-Rite Complete Swimquip Style Pool Lights": "Lights, Lighting, Niche type",
    "Pentair / Sta-Rite Complete U-3 Gunite Skimmers": "Skimmers",
    "Pentair / Sta-Rite Complete U-3 Standard Mouth Vinyl Liner Skimmers": "Skimmers",
    "Pentair / Sta-Rite Crystal-Flo II Top Mount Sand Filter System": "Filters, Sand, Top Mount",
    "Pentair / Sta-Rite Crystal-Flo Side Mount Sand": "Filters, Sand, Side Mount",
    "Pentair / Sta-Rite Crystal-Flo Top Mount Sand": "Filters, Sand, Top Mount",
    "Pentair / Sta-Rite Crystal-Flo Top Mount Sand, 30\", T-300BP-2": "Filters, Sand, Top Mount",
    "Pentair / Sta-Rite DEP & DEP-01B DE Filter": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite DEP & DEP-01B DE Filter Grid Assembly": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite DEPB DE Filter": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite DEPB DE Filter Grid Assembly": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite DES DE Filter": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite DES DE Filter Grid Assembly": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite GW9500, Inground": "Cleaners, Suction",
    "Pentair / Sta-Rite Great White, Model GW9000": "Cleaners, Suction",
    "Pentair / Sta-Rite HRP Series Sand, HRP-20, 24, 30": "Filters, Sand, Side Mount",
    "Pentair / Sta-Rite HRP-01B Series Sand, HRP20-01B, 24-01B, 30-01B": "Filters, Sand, Side Mount",
    "Pentair / Sta-Rite HRPB Series Sand, HRPB-20, 24, 30": "Filters, Sand, Side Mount",
    "Pentair / Sta-Rite In Ground Skimmers, U-3": "Skimmers",
    "Pentair / Sta-Rite Light, 5082, 5086": "Lights, Lighting, Niche type",
    "Pentair / Sta-Rite Lil Shark, Model GW8000": "Cleaners, Suction",
    "Pentair / Sta-Rite Max-E-Therm Heaters, SR200, 333, 400": "Gas Heaters, Heaters",
    "Pentair / Sta-Rite Modular DE, S7MD60, S7MD72": "Filters, DE, Module Type",
    "Pentair / Sta-Rite Multiport, 1-1/2\" WC112 Series": "Filter Valves, Valves, Top Mount",
    "Pentair / Sta-Rite PRC, PRD, Cartridge and DE Filters": "Filters, DE, Module Type",
    "Pentair / Sta-Rite Plastic Slide Valve": "Filter Valves, Valves, Push Pull",
    "Pentair / Sta-Rite Pool Shark, Models GW7500, GW7700": "Cleaners, Suction",
    "Pentair / Sta-Rite Posi-Clear Cartridge System, PXC75, 95, 125, 150": "Filters, Cartridge Type",
    "Pentair / Sta-Rite Posi-Flo II Cartridge, PTM-135": "Filters, Cartridge Type",
    "Pentair / Sta-Rite Posi-Flo II Cartridge, PTM-50, 70, 100": "Filters, Cartridge Type",
    "Pentair / Sta-Rite Posi-Flo SS Cartridge, 1 Piece Tank, TX Models": "Filters, Cartridge Type",
    "Pentair / Sta-Rite Posi-Flo SS Cartridge, 2 Piece Tank, TX, TXR Models": "Filters, Cartridge Type",
    "Pentair / Sta-Rite Sidemount": "Filter Valves, Valves, Side Mount",
    "Pentair / Sta-Rite Sidemount Valves": "Filter Valves, Valves, Side Mount",
    "Pentair / Sta-Rite Sunbrite Halogen Light": "Lights, Lighting, Niche type",
    "Pentair / Sta-Rite Sunbrite LTC Light": "Lights, Lighting, Niche type",
    "Pentair / Sta-Rite Sunburst Halogen Light": "Lights, Lighting, Niche type",
    "Pentair / Sta-Rite Sunglow Light": "Lights, Lighting, Niche type",
    "Pentair / Sta-Rite Sunstar AG Halogen Light": "Lights, Lighting, AG Thru Wall",
    "Pentair / Sta-Rite Swimquip Bronze Slide Valve": "Filter Valves, Valves, Push Pull",
    "Pentair / Sta-Rite Swimquip Multiport, 1-1/2\"": "Filter Valves, Valves, Top Mount",
    "Pentair / Sta-Rite System 2, Mod Media and Mod DE System, PLM & PLD Models": "Filters, DE, Module Type",
    "Pentair / Sta-Rite System 2, Modular DE, PLDE36, PLDE48": "Filters, DE, Module Type",
    "Pentair / Sta-Rite System 3 Cartridge, S7M120, S8M150, S7M400, S8M500": "Filters, Cartridge Type",
    "Pentair / Sta-Rite System 3 DE Filter": "Filters, DE, Grid Type",
    "Pentair / Sta-Rite System 3 Sand, S7S50, S8S70": "Filters, Sand, Side Mount",
    "Pentair / Sta-Rite Thermoplastic DE Separation Tank, 60SEP": "Seperation Tanks, Filters",
    "Pentair / Sta-Rite Top Mount 2\" ": "Filter Valves, Valves, Top Mount",
    "Pentair / Sta-Rite Unions": "Plumbing Unions, White Goods",
    "Pentair / Sta-Rite Vinyl Niche, 0568-0121 & 0568-0171": "Light Niches, Lighting",
    "Pentair Above Ground Hydro-Skim Skimmers": "Skimmers",
    "Pentair Aerators": "Aerators",
    "Pentair Amerlite Pool Light": "Lights, Lighting, Niche type",
    "Pentair Amerquartz Light": "Lights, Lighting, Niche type",
    "Pentair Aqualight Halogen": "Lights, Lighting, Niche type",
    "Pentair Aqualumin II, Aqualumin II Light": "Lights, Lighting, Aqualumin",
    "Pentair Aqualumin, Aqualumin II Mounting Bracket": "Lights, Lighting, Aqualumin",
    "Pentair Booster Pump, Current version, Model LAO1N": "Cleaners, Pressure",
    "Pentair CF Cartridge, CF-40, 60, 80": "Filters, Cartridge Type",
    "Pentair Cartridges, 13 Inch and over Diameter": "Filter Cartridges, Filters",
    "Pentair Challenger Pump": "Pumps",
    "Pentair Clean and Clear / Predator Cartridge System": "Filters, Cartridge Type",
    "Pentair Clean and Clear Plus Cartridge": "Filters, Cartridge Type",
    "Pentair Commercial Pool Control Parts, LX80, LX820": "Pool Controls, Automation",
    "Pentair Complete AQL Aqualuminator Above Ground Light and Return": "Lights, Lighting, Combo AG",
    "Pentair Complete Aqualumin III Vinyl Liner Mounting Brackets": "Lights, Lighting, Aqualumin",
    "Pentair Complete Intellibrite 5G White Pool Lights": "Lights, Lighting, Niche type",
    "Pentair Complete Intellibrite 5G White Spa Lights": "Lights, Lighting, Niche type",
    "Pentair Complete Plastic Niches": "Light Niches, Lighting",
    "Pentair Complete Quasar 500 Above Ground Pool Light": "Lights, Lighting, AG Thru Wall",
    "Pentair DE Filter Modules": "DE Filter Modules, Filters",
    "Pentair DM Cartridge, DM-75, 90, 120, 180, 240": "Filters, Cartridge Type",
    "Pentair Deck Jet I": "Deck Jets, White Goods",
    "Pentair Deck Jet II": "Deck Jets, White Goods",
    "Pentair EQ Commercial Pump": "Pumps",
    "Pentair Easytouch Pool Control Parts": "Pool Controls, Automation",
    "Pentair Fiberworks Lenses": "Lights, Lighting, Fiber Optic",
    "Pentair Fiberworks PG2000 Photon Generator": "Lights, Lighting, Fiber Optic",
    "Pentair Fiberworks Photon Generator": "Lights, Lighting, Fiber Optic",
    "Pentair Full Flow Valve": "Filter Valves, Valves, Push Pull",
    "Pentair Full Size SS Niches": "Light Niches, Lighting",
    "Pentair Hi-Lite Pool Light": "Lights, Lighting, Niche type",
    "Pentair Intellibrite 5G Color LED Pool Light - After 2009": "Lights, Lighting, Niche type",
    "Pentair Intellibrite 5G Color LED Spa Light - After 2009": "Lights, Lighting, Niche type",
    "Pentair Intellibrite White LED Pool Light - After 2009": "Lights, Lighting, Niche type",
    "Pentair Intellibrite, Colored LED Light": "Lights, Lighting, Niche type",
    "Pentair Intellibrite, White LED Light": "Lights, Lighting, Niche type",
    "Pentair Intellichlor": "Salt Chlorine Generators, Sanitization",
    "Pentair Intelliflo Pump, Models VS3050 and VF": "Pumps",
    "Pentair Intellipro Pump, Model VS 3050": "Pumps",
    "Pentair Intellitouch Pool Control Parts": "Pool Controls, Automation",
    "Pentair Jet Vac": "Cleaners, Pressure",
    "Pentair Junction Box": "Junction Boxes, White Goods",
    "Pentair Kreepy Krauly Sandshark": "Cleaners, Suction",
    "Pentair Kreepy Kruiser": "Cleaners, Suction",
    "Pentair Kreepy Legend II, LX5000G, Head Parts": "Cleaners, Pressure",
    "Pentair Legend II, LX-2000, Head Parts & Tune Up Kit": "Cleaners, Pressure",
    "Pentair Legend Platinum": "Cleaners, Pressure",
    "Pentair Legend, 3 Wheel Version, Parts & Tune Up Kits ": "Cleaners, Pressure",
    "Pentair Legend, 4 Wheel Version, Head Parts": "Cleaners, Pressure",
    "Pentair Legend, Hose and Back Up Valves": "Cleaners, Pressure",
    "Pentair Magic Stream Laminars": "Deck Jets, White Goods",
    "Pentair Mastertemp Heaters, 175 - 400": "Gas Heaters, Heaters",
    "Pentair Mastertemp Heaters, Electrical System": "Gas Heaters, Heaters",
    "Pentair Mastertemp Heaters, Water System": "Gas Heaters, Heaters",
    "Pentair Mini Max Heaters (1991 - 1997)": "Gas Heaters, Heaters",
    "Pentair Mini Max Heaters, Heat Exchangers, (1991 - 1997)": "Gas Heaters, Heaters",
    "Pentair Minimax AG Heaters, 75, 100, 100SC": "Gas Heaters, Heaters",
    "Pentair Minimax CH Heaters, 150 - 400": "Gas Heaters, Heaters",
    "Pentair Minimax Heaters, Burner Trays (1991 - 1997)": "Gas Heaters, Heaters",
    "Pentair Minimax NT Heaters, NT TSI, NT LN, NT STD, 200 - 400": "Gas Heaters, Heaters",
    "Pentair Minimax Plus Heaters, 150 - 400": "Gas Heaters, Heaters",
    "Pentair Mitra Stainless Cartridge, MA-60, 80, 100, 160": "Filters, Cartridge Type",
    "Pentair Mytilus B Fiberglass Cartridge, MY-60B, 80B, 100B": "Filters, Cartridge Type",
    "Pentair Mytilus FG Cartridge, MY-60, 80, 100": "Filters, Cartridge Type",
    "Pentair Mytilus Fiberglass Cartridge FMY-80, 100, 150": "Filters, Cartridge Type",
    "Pentair Nautilus FNS DE, FNS-24, 36, 48, 60": "Filters, DE, Grid Type",
    "Pentair Nautilus FNS Plus DE, 180006, 180007, 180008, 180009": "Filters, DE, Grid Type",
    "Pentair Nautilus Plus DE Stainless, NSP-36, 48, 60, 72": "Filters, DE, Grid Type",
    "Pentair Nautilus Stainless DE, NS-24, 36, 48, 60, 72": "Filters, DE, Grid Type",
    "Pentair Optiflo Pump, 3/4 to 1-1/2 HP": "Pumps",
    "Pentair PF Stainless Steel, Side Mount Sand PF-35, 50": "Filters, Sand, Side Mount",
    "Pentair Plastic Full Size and Small Niches": "Light Niches, Lighting",
    "Pentair Plastic Slide Valves": "Filter Valves, Valves, Push Pull",
    "Pentair Prowler 710": "Cleaners, Robotic",
    "Pentair Prowler 720, 730": "Cleaners, Robotic",
    "Pentair Quad DE, Models 60, 80, 100": "Filters, DE, Module Type",
    "Pentair Quick Niche": "Light Niches, Lighting",
    "Pentair R Series Commercial Pump, 5 to 15 HP": "Pumps",
    "Pentair Replacement Skimmer Lids with Thermometers": "Skimmers",
    "Pentair Return Line Eyeball Check Valves": "Inlet Fittings, Valves",
    "Pentair Round Starguard 8\" Mains Drains, Frame & Covers": "Main Drains, White Goods",
    "Pentair Sand Dollar Top Mount Sand System, SD-30 Thru SD-80": "Filters, Sand, Top Mount",
    "Pentair Sea Horse FG Cartridge, FSH-300, 400, 500": "Filters, Cartridge Type",
    "Pentair Sea Horse Stainless Cartridge SH-300, 400, 500": "Filters, Cartridge Type",
    "Pentair Separation Tank, S-20, S-30": "Seperation Tanks, Filters",
    "Pentair Small SS Niches": "Light Niches, Lighting",
    "Pentair Spectrum Amerlight, SAM": "Lights, Lighting, Niche type",
    "Pentair Spectrum Aqualight (SAL) Multicolor Spa Light": "Lights, Lighting, Niche type",
    "Pentair Star DE, ST-35, 40, 50, 80": "Filters, DE, Grid Type",
    "Pentair Suntouch Pool Control Parts": "Pool Controls, Automation",
    "Pentair Superflo Pump": "Pumps",
    "Pentair Tagelus Top Mount Sand, TA-35D thru TA-100D, TA30 Thur TA-60": "Filters, Sand, Top Mount",
    "Pentair Triton C-3 Side Mount Sand, TR100C-3, TR140C-3": "Filters, Sand, Side Mount",
    "Pentair Triton Commercial Side Mount Sand, TR100C, TR140C": "Filters, Sand, Side Mount",
    "Pentair Triton II Side Mount Sand, TR-40, 50, 60, 100, 100HD, 140": "Filters, Sand, Side Mount",
    "Pentair Valve Actuators": "Valve Actuators, Automation",
    "Pentair Warrior FG DE, 44, 66, 88 GPM": "Filters, DE, Grid Type",
    "Pentair and Hayward Insider Inlet Fittings": "Inlet Fittings, White Goods",
    "Replacement Skimmer Baskets": "Skimmers",
    "Vacuum Pole Parts": "Vacuum Poles, Maintenance",
    "Pentair / Rainbow Feeder Accessories" : "Chemical Feeders, Sanitization",
    "Pentar / American Products Autofills" : "Autofills, White Goods",
    "Pentair CPVC Check Valves" : "Check Valves, Valves",
    "Pentair / Rainbow Complete Dynamic Series Top Load Cartridge Filters" : "Cartridge Filters, Filters",
    "Pentair / Rainbow Complete Dynamic Series In Line Cartridge Filters" : "Cartridge Filters, Filters",
    "Pentair / Rainbow Dynamic Series I Inline Cartridge Filter" : "Cartridge Filters, Filters",
    "Pentair / Rainbow Series IV Cartridge Filter, DFM & DFML" : "Cartridge Filters, Filters",
    "Pentair / Rainbow Dynamic Series II & III Top Load Cartridge Filters" : "Cartridge Filters, Filters",
    "Pentair / Rainbow Module Cartridge Filter" : "Cartridge Filters, Filters",
    "Pentair / Rainbow High Capacity Automatic Feeders" : "Feeders, Sanitization",
    "Pentair / Sta-Rite Sunsaver Halogen Light": "Lighting",
    "Pentair / Pac-Fab Hatteras Pool Light" : "Lighting"
}

APS_HEADERS = {
    "sku":"",
    "part_number":"",
    "oem":"",
    "title":"",
    "description":"",
    "type":"",
    "category":"",
    "subcategory":"",
    "manufacturer":"",
    "cost":"",
    "list_price":"",
    "available":"",
    "obsolete":"",
    "weight":"",
    "height":"",
    "length":"",
    "width":"",
    "uom":"",
    "parent":"",
    "image_url":"",
    "scp_cost":"",
    "scp_category":"",
    "scp_sku":"",
    "optimus_cost":"",
    "optimus_sku":"",
    "optimus_category":""
}

_CLEANCATS = {
    "pentairamericanproductspushpullvalve":"Filter Valves, Valves, Push Pull",
    "partsautomaticcleaners":"Parts, Automatic Cleaners, Cleaners",
    "pentairpurextahitiantopmounthr212531":"Filters, Sand, Top Mount",
    "rails":"Rails, Deck Accessories",
    "pentairrainbowinlinefeeders":"Chemical Feeders, Sanitization",
    "pentairkreepylegendiilx5000gheadparts":"Cleaners, Pressure",
    "pentairamericanproductspredatorcartridge":"Filters, Cartridge Type",
    "compoolpentairpoolcontrolsystemcircuitboards":"Pool Controls, Automation",
    "filterscartridge":"Filters, Cartridge",
    "pentairstariteposiflosscartridge2piecetanktxtxrmodels":"Filters, Cartridge Type",
    "pentairlegendiilx2000headpartstuneupkit":"Cleaners, Pressure",
    "replacementdegrids":"Replacement, DE, Grid, Filters",
    "pentaircartridges13inchandoverdiameter":"Filter Cartridges, Filters",
    "pentaircfcartridgecf406080":"Filters, Cartridge Type",
    "pentairstaritelilsharkmodelgw8000":"Cleaners, Suction",
    "miscellaneouselectrical":"White Goods, electrical",
    "heatersgascommercial":"Heaters Gas, Commercial, Heaters",
    "chemicalssanitizer":"Sanitizer, Chemicals",
    "pentairstaritesystem2modmediaandmoddesystemplmpldmodels":"Filters, DE, Module Type",
    "servicerepairinstall":"Service Repair Install, Maintenance",
    "pentairaqualighthalogen":"Lights, Lighting, Niche type",
    "pentaircompleteaqlaqualuminatorabovegroundlightandreturn":"Lights, Lighting, Combo AG",
    "pentairrainbowprovac":"Vacuum Heads, Maintenance",
    "miscellaneousmaintenance":"Miscellaneous, Maintenance",
    "pentairpacfabhiflow2":"Filter Valves, Valves, Side Mount",
    "pentairpurexquietfloaquatron":"Pumps",
    "designersconces":"Accessories, sconce",
    "pumps":"Pumps",
    "pentaircompleteaqualuminiiivinyllinermountingbrackets":"Lights, Lighting, Aqualumin",
    "filters":"Filters",
    "pentairrainbowfeederaccessories":"Chemical Feeders, Sanitization",
    "pentairstariteposiclearcartridgesystempxc7595125150":"Filters, Cartridge Type",
    "pentairminimaxheatersburnertrays19911997":"Gas Heaters, Heaters",
    "pentairrainbowfloatingfeeders":"Floating Chemical Feeders, Sanitization",
    "valveactuators":"Valve Actuators, Automation",
    "filtervalvespushpull":"Filter Valves, Push Pull, Valves",
    "pentairrainbowmodulecartridgefilter":"Cartridge Filters, Filters",
    "portablevacuumsystemslinervac":"Portable Vacuum Systems Liner Vac, Maintenance",
    "pentairpurextahitianvalve":"Filter Valves, Valves, Top Mount",
    "covers":"Covers",
    "pentairletroautofillst40t40fn":"Autofills, White Goods",
    "sanitization":"Sanitization",
    "pentairpurextropicisleheaters120300":"Gas Heaters, Heaters",
    "motorspumps":"Pumps, motor",
    "pentairstaritecompleteswimquipstylepoollights":"Lights, Lighting, Niche type",
    "pentairprahervalves2":"Filter Valves, Valves, Top Mount",
    "pentairstaritecompleteu3standardmouthvinyllinerskimmers":"Skimmers",
    "electricspaheatersstandalone":"Heaters, Electric, Spa, Equipment",
    "valves":"Valves",
    "pentairpurexsmbw10002000seriesdestainless":"Filters, DE, Grid Type",
    "pentairsuperflopump":"Pumps",
    "pentairamericancompletespectrumaqualightpoolandspalights":"Lights, Lighting, Niche type",
    "pentairaqualuminiiaqualuminiilight":"Lights, Lighting, Aqualumin",
    "filtervalvessidemount":"Filter Valves, Side Mount, Valves",
    "pentairpfstainlesssteelsidemountsandpf3550":"Filters, Sand, Side Mount",
    "pentairamericancompletesmallstainlesssteelniches":"Light Niches, Lighting",
    "pentairstaritesystem3cartridges7m120s8m150s7m400s8m500":"Filters, Cartridge Type",
    "escutcheons":"Escutcheons, Deck Accessories",
    "pentairstaritedepdep01bdefiltergridassembly":"Filters, DE, Grid Type",
    "motorsresidential":"Motors, Residential, Pumps",
    "miscellaneousspa":"Spa, Accessories, part",
    "antientrapmentmaindrainscommercial":"Anti-Entrapment Main Drains, Commercial, White Goods",
    "pentairamericanproductstitancmdefilter":"Filters, DE, Grid Type",
    "compoolpentairpoolcontrolsystemspasideremotes":"Pool Controls, Automation",
    "fillspouts":"Fillspouts, Deck Accessories",
    "pentairdefiltermodules":"DE Filter Modules, Filters",
    "seperationtanks":"Seperation Tanks, Filters",
    "pentairmytilusfiberglasscartridgefmy80100150":"Filters, Cartridge Type",
    "filtersystemscartridge":"Filter Systems, Cartridge, Filters",
    "pentairmastertempheaterselectricalsystem":"Gas Heaters, Heaters",
    "pentairrainbowcompletedsfseriesskimfilters":"Skimmers",
    "partsplumbing":"Parts, Plumbing, White Goods",
    "deckdrainsdeckjointsdeckgrates":"Deck Drains Deck Joints Deck Grates, White Goods",
    "compoolpentairpoolcontrolsystemparts":"Pool Controls, Automation",
    "pentairpacfacdynamopump":"Pumps",
    "pentaireasytouchpoolcontrolparts":"Pool Controls, Automation",
    "pentairnautilusfnsplusde180006180007180008180009":"Filters, DE, Grid Type",
    "poollift":"Pool Lift, Deck Accessories",
    "replacementcartridges":"Replacement, Cartridges, Filters, Cartridge",
    "purexfilterparts":"Filters, part",
    "pentairmastertempheaterswatersystem":"Gas Heaters, Heaters",
    "aquaticchair":"Aquatic Chair, Deck Accessories",
    "pentairrainbowcompletehighcapacityfeeders":"Chemical Feeders, Sanitization",
    "pentairhydrelcompletehalogenspaandpoollights":"Lights, Lighting, Niche type",
    "returninletfittings":"Return Inlet Fittings, White Goods",
    "filtercartridges":"Filter Cartridges, Filters",
    "pentairaerators":"Aerators",
    "pentaireqcommercialpump":"Pumps",
    "pentairfiberworksphotongenerator":"Lights, Lighting, Fiber Optic",
    "toolaccessories":"Tool Accessories, Maintenance",
    "waterfall":"Water Features, Deck Accessories",
    "filtersde":"Filters, DE",
    "pentairstaritecrystalflotopmountsand":"Filters, Sand, Top Mount",
    "pentairpacfabingroundbermudaskimmers":"Skimmers",
    "jandyfilterparts":"Filters, part",
    "pentairamerquartzlight":"Lights, Lighting, Niche type",
    "automaticcleaners":"Cleaners",
    "partswhitegoodsflowfittings":"Parts, White Goods, Flow Fittings",
    "pvcfittings":"PVC Fittings, White Goods",
    "chemicalfeederswatermatic":"Sanitization, feeder, chemical feeder",
    "fittingsbrass":"Fittings - Brass, White Goods, PVC",
    "replacementbulbs":"Replacement Bulb, bulb, Lighting",
    "divingboards":"Diving Boards, Deck Accessories",
    "pentaircleanandclearpluscartridge":"Filters, Cartridge Type",
    "pentairstaritesystem3sands7s50s8s70":"Filters, Sand, Side Mount",
    "pentairamericanproductsseparationtanks":"Seperation Tanks, Filters",
    "partsheaterscommercial":"Parts, Heaters, Commercial",
    "pentairpurexstainlessdeseparationtanksep487296144":"Seperation Tanks, Filters",
    "whitegoodsflowfittings":"White Goods",
    "pentairkreepykraulyezvac":"Cleaners, Suction",
    "cleanerselectricrobotic":"Cleaners, Robotic",
    "pentairkreepykraulykadet":"Cleaners, Suction",
    "controlsystems":"Control Systems, Automation",
    "pentairpurexwhisperflopumpmodelswfwfe":"Pumps",
    "partsmaintenance":"Parts, Maintenance",
    "pentairprahervalves112":"Filter Valves, Valves, Top Mount",
    "airblowers":"Air Blowers, spa, wholegood",
    "pentairroundstarguard8mainsdrainsframecovers":"Main Drains, White Goods",
    "maindrainscommercial":"White Goods",
    "pentairfiberworkspg2000photongenerator":"Lights, Lighting, Fiber Optic",
    "filtervalvestopmount":"Filter Valves, Top Mount, Valves",
    "heatpumps":"Heat Pumps",
    "vacuumsall":"Vacuums, All, Maintenance",
    "filtersdeperflextype":"Filters, DE, Perflex Type",
    "pentairminimaxchheaters150400":"Gas Heaters, Heaters",
    "pentairrseriescommercialpump5to15hp":"Pumps",
    "pentairseparationtanks20s30":"Seperation Tanks, Filters",
    "heatpumpscomm":"Heat Pumps, commercial, unit",
    "pentairkreepykrauly1994tocurrentaccessories":"Cleaners, Suction",
    "pentairamericanproductsdivertervalveparts":"Plumbing Valves, Valves",
    "vacuumheads":"Vacuum Heads, Maintenance",
    "pentairstaritevinylniche0568012105680171":"Light Niches, Lighting",
    "pentairstaritesunbritehalogenlight":"Lights, Lighting, Niche type",
    "testingequipment":"Maintenance, testing",
    "pentairmastertempheaters175400":"Gas Heaters, Heaters",
    "automation":"Automation",
    "autofills":"White Goods, autofill, auto fill",
    "pentairamericanproductscommandercartridge":"Filters, Cartridge Type",
    "filterscartridgetype":"Filters, Cartridge Type",
    "pentaircompooldivertervalveparts":"Plumbing Valves, Valves",
    "pentairstaritedepbdefiltergridassembly":"Filters, DE, Grid Type",
    "electrical":"Electrical",
    "vacuumreleasesystems":"Vacuum Release Systems, White Goods",
    "pentairspectrumamerlightsam":"Lights, Lighting, Niche type",
    "spamisc":"White Goods, Spa",
    "heaters":"Heaters",
    "pentairintellitouchpoolcontrolparts":"Pool Controls, Automation",
    "pentairletroinlinethermometers":"Thermometers, Accessories",
    "miscellaneousdeckequipment":"Miscellaneous, Deck Accessories",
    "poolservice":"Maintenance",
    "transferrails":"Transfer Rails, Deck Accessories",
    "cleanersrobotic":"Cleaners, Robotic",
    "letropentairboosterpumpolderversion":"Cleaners, Pressure, Pump",
    "maintenanceequip":"Maintenance",
    "partsfilter":"Parts, Filter, Filters",
    "miscellaneousspachemical":"Chemicals, Spa",
    "pentairpurexsmsmbw4000seriesde":"Filters, DE, Grid Type",
    "pentairkreepykrauly1994andprior":"Cleaners, Suction",
    "pentairstariteposifloiicartridgeptm135":"Filters, Cartridge Type",
    "miscellaneousfilter":"Filters, part, accessory",
    "pentairamericanproductsultraflopump":"Pumps",
    "miscellaneouswhitegoodsflowfittingscomm":"Miscellaneous, White Goods, Flow Fittings, Comm",
    "inpoolfountains":"Accessories, fountain, water feature",
    "pentaircommercialpoolcontrolpartslx80lx820":"Pool Controls, Automation",
    "pentairtritoniisidemountsandtr405060100100hd140":"Filters, Sand, Side Mount",
    "gaskets":"Gaskets, O-Rings & Gaskets",
    "pentairkreepykruiser":"Cleaners, Suction",
    "pentairminimaxplusheaters150400":"Gas Heaters, Heaters",
    "chemicalfeeders":"Chemical Feeders, Sanitization",
    "heaterselectric":"Heaters, Electric",
    "pentairletroemersoncleanerpumpreplacementmotors":"Pump Motors, Pumps",
    "pentairsuntouchpoolcontrolparts":"Pool Controls, Automation",
    "heaters":"Heaters",
    "pentairstaritecrystalfloiitopmountsandfiltersystem":"Filters, Sand, Top Mount",
    "pentairrainbowfreestandingfeeders":"Chemical Feeders, Sanitization",
    "pentairamericanproductssidemount112":"Filter Valves, Valves, Side Mount",
    "escutcheon":"Escutcheon, Deck Accessories",
    "pentairstaritesystem3defilter":"Filters, DE, Grid Type",
    "miscfeederschlorinatorssanitizerscomm":"Sanitization, chlorinator, feeder",
    "waterfeatures":"Deck Accessories, water features",
    "decklaminarjets":"Deck Accessories, water feature, jet",
    "parts":"Parts, Deck Accessories",
    "pentairrainbowflexvacheads":"Vacuum Heads, Maintenance",
    "haywardandpentairdeckgutterdrains":"Deck and Gutter Drains, White Goods",
    "miscellaneousfeederschlorinatorssantizers":"Sanitization, Feeders Chlorinators Santizers",
    "spaaccessorieshardware":"Spa Accessories Hardware, Accessories",
    "pentairstariteabgseriespump":"Pumps",
    "gokits":"Go-Kits, O-Rings & Gaskets, kit",
    "miscellaneouswhitegoodsflowfittingscomm":"Miscellaneous, White Goods, Flow Fittings, Commercial",
    "pentaircompoolcompletedivertervalves":"Plumbing Valves, Valves",
    "pentairstardest35405080":"Filters, DE, Grid Type",
    "pentairhydrelsunliteniche":"Light Niches, Lighting",
    "pentairamericancompleteaqualuminiiipoollights":"Lights, Lighting, Niche type",
    "pentairrainbowvinylvac":"Vacuum Heads, Maintenance",
    "skimmers":"Skimmers",
    "miscellaneousvacuumheadparts":"Vacuum Heads, Maintenance",
    "pentairstaritecrystalflosidemountsand":"Filters, Sand, Side Mount",
    "pentairstaritedepbdefilter":"Filters, DE, Grid Type",
    "solarreels":"Accessories, cover, solar reel",
    "plumbingvalvesunions":"Plumbing Valves Unions, Valves",
    "heaterventing":"Heater Venting, Heaters",
    "niches":"Niches, Lighting",
    "cleanerspopup":"Cleaners, infloor",
    "pentairstaritesidemount":"Filter Valves, Valves, Side Mount",
    "pentairabovegroundhydroskimskimmers":"Skimmers",
    "pentairrainbowseriesivcartridgefilterdfmdfml":"Cartridge Filters, Filters",
    "partsfeederschlorinatorssanitizers":"Sanitization, Parts, Feeders Chlorinators Sanitizers",
    "pentairamericanproductsquantumcmseriescartridge":"Filters, Cartridge Type",
    "pentairamericanproductsquantumstainlesssteelcartridge":"Filters, Cartridge Type",
    "whitegoods":"White Goods",
    "pentairrainbowhighcapacityautomaticfeeders":"Feeders, Sanitization",
    "pentairletroaosmithmagnetekcleanerpumpmotors":"Pump Motors, Pumps",
    "filtersdegridtype":"Filters, DE, Grid Type",
    "feederschlorinatorssantizers":"Sanitization",
    "pentairreplacementskimmerlidswiththermometers":"Skimmers",
    "pentairlegendhoseandbackupvalves":"Cleaners, Pressure",
    "pentairplasticslidevalves":"Filter Valves, Valves, Push Pull",
    "pentairrainbowdynamicseriesiiiiitoploadcartridgefilters":"Cartridge Filters, Filters",
    "filterssandtopmount":"Filters, Sand, Top Mount, Valves",
    "pentairprahercompletevalves":"Filter Valves, Valves, Side Mount",
    "pentairkreepykraulythruster":"Cleaners, Suction",
    "pentairamericanproductssandpiperfiltersidemount":"Filters, Sand, Side Mount",
    "pentairstariteposifloiicartridgeptm5070100":"Filters, Cartridge Type",
    "pentairamericanproductsamericanapump":"Pumps",
    "pentairstaritesunsaverhalogenlight":"Lighting",
    "plumbingall":"White Goods",
    "pentairjetvac":"Cleaners, Pressure",
    "therapeuticbars":"Therapeutic Bars, Deck Accessories",
    "defiltermodules":"DE Filter Modules, Filters",
    "pentairdeckjeti":"Deck Jets, White Goods",
    "pentairnautilusstainlessdens2436486072":"Filters, DE, Grid Type",
    "cleanerssuction":"Cleaners, Suction",
    "saltchlorinegenerators":"Sanitization, salt",
    "pentairpacfab2slidevalve":"Filter Valves, Valves, Push Pull",
    "pentairrainbowdynamicseriesiinlinecartridgefilter":"Cartridge Filters, Filters",
    "tools":"Maintenance, Tool",
    "pentairmytilusfgcartridgemy6080100":"Filters, Cartridge Type",
    "pentairamerlitepoollight":"Lights, Lighting, Niche type",
    "pentairamericancompleteaqualuminatorabovegroundpoollightandreturn":"Lights, Lighting, Combo AG",
    "pentairamericanproductssidemount2":"Filter Valves, Valves, Side Mount",
    "filterssandcommercial":"Filters, Sand, Commercial",
    "pentairminimaxheaters19911997":"Gas Heaters, Heaters",
    "pentairpurex2000seriesbackwashvalve":"Filter Valves, Valves, Bottom Mount",
    "bulkfiber":"Bulk Fiber, Lighting",
    "nonchemicalsanitizer":"Sanitization",
    "pentairtagelustopmountsandta35dthruta100dta30thurta60":"Filters, Sand, Top Mount",
    "junctionbox":"Junction Box, White Goods",
    "pentaramericanproductsautofills":"Autofills, White Goods",
    "pipeflex":"PVC, White Goods, Plumbing",
    "pentairpacfabtopmountvalve112":"Filter Valves, Valves, Top Mount",
    "pentairlegend4wheelversionheadparts":"Cleaners, Pressure",
    "pentairfilterparts":"Filters, part",
    "pentairnautilusfnsdefns24364860":"Filters, DE, Grid Type",
    "pentairrainbowbrominefeeder":"Chemical Feeders, Sanitization",
    "pentairrainbowsuperprovacmodel241":"Vacuum Heads, Maintenance",
    "plumbingunions":"Plumbing Unions, White Goods",
    "pentairprowler710":"Cleaners, Robotic",
    "spaaccessoriescompproducts":"Spa, Accessories",
    "pentairstariteingroundskimmersu3":"Skimmers",
    "pentairstariteunions":"Plumbing Unions, White Goods",
    "lubes":"Lubes, Accessories",
    "deckequipment":"Deck Accessories",
    "pentairquaddemodels6080100":"Filters, DE, Module Type",
    "pentairspectrumaqualightsalmulticolorspalight":"Lights, Lighting, Niche type",
    "coverswinter":"Covers, Winter",
    "filterssandsidemount":"Filters, Sand, Side Mount, Valves",
    "lightniches":"Light Niches, Lighting",
    "strainerscommercial":"Strainers, Commercial, White Goods",
    "pentaircompleteintellibrite5gwhitepoollights":"Lights, Lighting, Niche type",
    "pentairmytilusbfiberglasscartridgemy60b80b100b":"Filters, Cartridge Type",
    "pentairboosterpumpcurrentversionmodellao1n":"Cleaners, Pressure",
    "pentairstaritesunbriteltclight":"Lights, Lighting, Niche type",
    "pentairmitrastainlesscartridgema6080100160":"Filters, Cartridge Type",
    "pentairstaritethermoplasticdeseparationtank60sep":"Seperation Tanks, Filters",
    "pentairamericanproductsmaximpump":"Pumps",
    "pentairstariteprcprdcartridgeanddefilters":"Filters, DE, Module Type",
    "filteraccessories":"Filters, Accessories",
    "pentairstariteposiflosscartridge1piecetanktxmodels":"Filters, Cartridge Type",
    "lighting":"Lighting",
    "partswhitegoodsflowfittingscommercail":"Parts, White Goods, Flow Fittings, Commercail",
    "pentairstaritelight50825086":"Lights, Lighting, Niche type",
    "illuminators":"Illuminators, Lighting",
    "pentairstaritehrpseriessandhrp202430":"Filters, Sand, Side Mount",
    "partsfilteraccessories":"Parts, Filters, Accessories",
    "pentairamericancompletespectrumamerlitepoollights":"Lights, Lighting, Niche type",
    "accessories":"Accessories",
    "pentairpacfabhatteraspoolniche":"Light Niches, Lighting",
    "chemfeeders":"Chem Feeders, Sanitization",
    "pentaircompleteplasticniches":"Light Niches, Lighting",
    "pentairreturnlineeyeballcheckvalves":"Inlet Fittings, Valves",
    "pentairrainbowleaftrapmodel186":"Leaf Traps, Accessories, Cleaner",
    "pentairstaritehrpbseriessandhrpb202430":"Filters, Sand, Side Mount",
    "checkvalves":"Valves, check, check valve",
    "pentairamericancompletespabritespalights":"Lights, Lighting, Niche type",
    "ortegapentairtstyledivertervalves":"Plumbing Valves, Valves",
    "pentairamericanproductsaqualuminatorquasarquasar500":"Lights, Lighting, Combo AG",
    "pentairkreepykraulysandshark":"Cleaners, Suction",
    "spraymarkingpaint":"Spray Paint, Accessories, Part",
    "pentairpacfabhydropump590700series":"Pumps",
    "replacementskimmerbaskets":"Skimmers",
    "controls":"Controls, Automation",
    "pentaircpvccheckvalves":"Check Valves, Valves",
    "designerfountains":"Designer Fountains, Accessories",
    "vacuumpoleparts":"Vacuum Poles, Maintenance",
    "rubberbumper":"Rubber Bumper, Deck Accessories",
    "vacuumhoseparts":"Maintenance, vacuum, part",
    "poolaccessequipment":"Pool Access Equipment, Deck Accessories",
    "motorscomm":"Motors, Comm, Pumps",
    "partslightsautocontrollers":"Parts, Lights Auto Controllers, Lighting",
    "lightsnichetype":"Lights, Niche type, Lighting",
    "pentairstaritehrp01bseriessandhrp2001b2401b3001b":"Filters, Sand, Side Mount",
    "poolcontrols":"Automation, control",
    "pentairamericanproductseclipsemeteortopmount":"Filters, Sand, Top Mount",
    "maindrains":"Main Drains, White Goods",
    "pentairstariteswimquipmultiport112":"Filter Valves, Valves, Top Mount",
    "pentairandhaywardinsiderinletfittings":"Inlet Fittings, White Goods",
    "miscellaneousplumbing":"Miscellaneous, Plumbing, White Goods",
    "pentairstaritegreatwhitemodelgw9000":"Cleaners, Suction",
    "pentairtritonc3sidemountsandtr100c3tr140c3":"Filters, Sand, Side Mount",
    "pentairstaritecrystalflotopmountsand30t300bp2":"Filters, Sand, Top Mount",
    "jumpstand":"Jump Stand, Deck Accessories",
    "poolspalightingautocontrollers":"Lighting, Auto Controllers",
    "stanchions":"Stanchions, Deck Accessories",
    "leaftrappers":"Cleaners, accessory, leaf trap",
    "pentairchallengerpump":"Pumps",
    "pentairrainbowcompleteinlinefeeders":"Chemical Feeders, Sanitization",
    "leafvacs":"Maintenance, leaf vac, vacuum",
    "pentairwarriorfgde446688gpm":"Filters, DE, Grid Type",
    "pentairsmallssniches":"Light Niches, Lighting",
    "pentairstaritecalypsomodelgw7000":"Cleaners, Suction",
    "pentairamericanproducts6positiontopmount":"Filter Valves, Valves, Top Mount",
    "cleaners":"Cleaners",
    "pentairintelliflopumpmodelsvs3050andvf":"Pumps",
    "pumpsresidential":"Pumps, Residential",
    "waterfeatures":"Water Features, Deck Accessories",
    "pentairdmcartridgedm7590120180240":"Filters, Cartridge Type",
    "saltgeneratorscommercial":"Salt Generators, Commercial, Sanitization",
    "pentairminimaxheatersheatexchangers19911997":"Gas Heaters, Heaters",
    "partsspa":"Parts, Spa, White Goods",
    "pentairpacfabingroundskimcleanskimmers":"Skimmers",
    "pentairkreepykrauly1993andprioraccessories":"Cleaners, Suction",
    "partswaterfeatures":"White Goods, water feature, part",
    "teststrips":"Maintenance, testing, water testing, test strip",
    "pentairmagicstreamlaminars":"Deck Jets, White Goods",
    "pentairkreepykrauly19941999":"Cleaners, Suction",
    "inletfittings":"Inlet Fittings, White Goods",
    "pentairlegend3wheelversionpartstuneupkits":"Cleaners, Pressure",
    "spablowers":"Air Blowers, spa, wholegood",
    "pentairstariteswimquipinletfitting":"Inlet Fittings, White Goods",
    "chlorinatorsfloatingdispensers":"Chlorinators Floating Dispensers, Sanitization",
    "filtersystemsde":"Filter Systems, DE, Filters",
    "plumbingfittings":"White Goods, Plumbing",
    "testmeterslabs":"Test Meters Labs, Maintenance, testing",
    "ladders":"Ladders, Deck Accessories",
    "pentairsanddollartopmountsandsystemsd30thrusd80":"Filters, Sand, Top Mount",
    "pentairamericanproductstitanssdefilter":"Filters, DE, Grid Type",
    "storagereels":"Storage Reels, Deck Accessories",
    "pentairamericanproducts5and8positiontopmount":"Filter Valves, Valves, Top Mount",
    "filterscartridgecommercial":"Filters, Cartridge, Commercial",
    "diving":"Diving, Deck Accessories",
    "pentairstaritemaxethermheaterssr200333400":"Gas Heaters, Heaters",
    "nutsboltsscrews":"Nuts Bolts Screws, Maintenance",
    "pentairstaritemultiport112wc112series":"Filter Valves, Valves, Top Mount",
    "pentairstaritedesdefiltergridassembly":"Filters, DE, Grid Type",
    "pentairfullflowvalve":"Filter Valves, Valves, Push Pull",
    "filtercontrolvalves":"Filter Control Valves, Valves",
    "pentairfiberworkslenses":"Lights, Lighting, Fiber Optic",
    "deckconstruction":"Deck Accessories",
    "pentairprowler720730":"Cleaners, Robotic",
    "servicerepairinstallparts":"Maintenance",
    "pentairvalveactuators":"Valve Actuators, Automation",
    "partsmiscellaneousdeckequipment":"Parts, Miscellaneous, Deck Accessories",
    "lightsthruwallspa":"Lighting, wholegood, spa",
    "pentairamericancompletefullsizestainlesssteelniches":"Light Niches, Lighting",
    "testplugs":"Test Plugs, White Goods",
    "pentairstaritegw9500inground":"Cleaners, Suction",
    "pentairstaritesystem2modulardeplde36plde48":"Filters, DE, Module Type",
    "pentairrainbowcompletedynamicseriesinlinecartridgefilters":"Cartridge Filters, Filters",
    "pentairstarite4suctiontrappackage142175":"Pumps",
    "plumbingvalvesunionscommercial":"Plumbing Valves Unions, Commercial, Valves",
    "pentairamericanproductssmallskimmersfas100":"Skimmers",
    "anchors":"Anchors, Deck Accessories",
    "pentairtritoncommercialsidemountsandtr100ctr140c":"Filters, Sand, Side Mount",
    "pentairintellichlor":"Salt Chlorine Generators, Sanitization",
    "pentairseahorsestainlesscartridgesh300400500":"Filters, Cartridge Type",
    "lifeguardchairs":"Lifeguard Chairs, Deck Accessories",
    "ortegavalveparts":"Valves, part, ortega",
    "pentairfullsizessniches":"Light Niches, Lighting",
    "pentairintellibritecoloredledlight":"Lights, Lighting, Niche type",
    "saltgenerators":"Salt Generators, Sanitization",
    "pentairpurexcfwcartridgecfw120180315405":"Filters, Cartridge Type",
    "pumpmotors":"Pumps, Motor",
    "pentairpurexcseriescommericialpump":"Pumps",
    "partspumps":"Parts, Pumps",
    "pentairrainbowdsfskimfilter":"Skimmers",
    "pentairoptiflopump34to112hp":"Pumps",
    "boards":"Boards, Deck Accessories",
    "plumbingvalves":"Plumbing Valves, White Goods",
    "pentairstaritecompleteu3guniteskimmers":"Skimmers",
    "poolspalights":"Pool Spa Lights, Lighting",
    "cleanersinfloor":"Cleaners, infloor",
    "partsheaters":"Parts, Heaters",
    "pentairstariteabovegroundskimmers096556403096557403":"Skimmers",
    "pentairamericanproductseaglepump":"Pumps",
    "pentairintellibritewhiteledpoollightafter2009":"Lights, Lighting, Niche type",
    "leafvacsvariousmodels":"Leaf Vacs, Vacuum, Maintenance",
    "pentairamericanproductsingroundadmiralskimmers":"Skimmers",
    "plumbing":"Plumbing, White Goods, part",
    "pentairpacfabhatteraspoollight":"Lighting",
    "spacontrolscomponents":"Spa, Automation",
    "pentairamericanproductstitanrpmdefilter":"Filters, DE, Grid Type",
    "alarmspoolentry":"Alarm, Pool Entry, Safety, Accessories",
    "pentairkreepykrauly2000tocurrent":"Cleaners, Suction",
    "pentairminimaxagheaters75100100sc":"Gas Heaters, Heaters",
    "cleanerscommercial":"Cleaners, Commercial",
    "led":"Lighting, LED",
    "haywardandpentairsafetyvaclocks":"Cleaners, Accessory",
    "toolshand":"Tools, Hand, Maintenance",
    "pentairpurexcmfcartridgecfm120180315":"Filters, Cartridge Type",
    "pumpscommercial":"Pumps, Commercial",
    "pentairseahorsefgcartridgefsh300400500":"Filters, Cartridge Type",
    "pentaircompleteintellibrite5gwhitespalights":"Lights, Lighting, Niche type",
    "safety":"Safety",
    "treads":"Treads, Deck Accessories",
    "pentairaqualuminaqualuminiimountingbracket":"Lights, Lighting, Aqualumin",
    "pentaircleanandclearpredatorcartridgesystem":"Filters, Cartridge Type",
    "pentairquickniche":"Light Niches, Lighting",
    "pentairintellibritewhiteledlight":"Lights, Lighting, Niche type",
    "pentairintellibrite5gcolorledpoollightafter2009":"Lights, Lighting, Niche type",
    "startingplatform":"Starting Platform, Deck Accessories",
    "pentairrainbowcompletedynamicseriestoploadcartridgefilters":"Cartridge Filters, Filters",
    "phandorpcontrollers":"PH and ORP Controllers, Automation",
    "filtersdemoduletype":"Filters, DE, Module Type",
    "pentairstaritedepdep01bdefilter":"Filters, DE, Grid Type",
    "pentairkreepykraulylegendmodelll505g":"Cleaners, Pressure",
    "spajets":"Spa, Jets, White Goods",
    "pentairpacfabpinnaclepump":"Pumps",
    "pentairrainbowleaftrapmodel179179c":"Leaf Traps, Accessories, Cleaner",
    "deckandgutterdrains":"Deck and Gutter Drains, White Goods",
    "pentairjunctionbox":"Junction Boxes, White Goods",
    "orings":"O-Rings & Gaskets",
    "pentairhilitepoollight":"Lights, Lighting, Niche type",
    "filterssand":"Filters, Sand",
    "pentairstaritesunstaraghalogenlight":"Lights, Lighting, AG Thru Wall",
    "pentairstaritetopmount2":"Filter Valves, Valves, Top Mount",
    "filtercontrolvalvescommercial":"Filter Control Valves, Commercial, Valves",
    "deckjets":"Deck Accessories, jet",
    "poolsafteydevices":"Pool Saftey Devices, Safety, Accessories",
    "pentairamericancompleteamerlitepoollights":"Lights, Lighting, Niche type",
    "pentairdeckjetii":"Deck Jets, White Goods",
    "chemfeederscommercial":"Chem Feeders, Commercial, Sanitization",
    "pentairstaritedesdefilter":"Filters, DE, Grid Type",
    "pentairstaritesidemountvalves":"Filter Valves, Valves, Side Mount",
    "pentairamericanproductseclipsesidemount":"Filters, Sand, Side Mount",
    "testkitsreagents":"Test Kits, Reagents, Maintenance",
    "separationtanks":"Separation Tank, Filters",
    "slides":"Slides, Deck Accessories",
    "partspumpscommercial":"Parts, Pumps, Commercial",
    "filtersystemssand":"Filter Systems, Sand, Filters",
    "pentairrainbowcompleteofflinefeeders":"Chemical Feeders, Sanitization",
    "pumps":"Pumps",
    "gasheaters":"Gas Heaters, Heaters",
    "pentairstariteplasticslidevalve":"Filter Valves, Valves, Push Pull",
    "pentaircompletequasar500abovegroundpoollight":"Lights, Lighting, AG Thru Wall",
    "pentairrainbowswivelwheelflexvac":"Vacuum Heads, Maintenance",
    "pressurevacuumgauges":"Accessories, gauge",
    "pentairkreepyezvackadetaccessories":"Cleaners, Suction",
    "pentairstaritemodulardes7md60s7md72":"Filters, DE, Module Type",
    "miscellaneouswaterfeatures":"Deck Accessories",
    "pentairamericancompleteaqualightspaandpoollights":"Lights, Lighting, Niche type",
    "pentairminimaxntheatersnttsintlnntstd200400":"Gas Heaters, Heaters",
    "pentairamericanproductsquantumrpmcartridge":"Filters, Cartridge Type",
    "pentairnautilusplusdestainlessnsp36486072":"Filters, DE, Grid Type",
    "lightsagthruwall":"Lights, AG Thru Wall, Lighting",
    "pentairlegendplatinum":"Cleaners, Pressure",
    "games":"Games, Deck Accessories",
    "cleanerspressure":"Cleaners, Pressure",
    "pentairintellibrite5gcolorledspalightafter2009":"Lights, Lighting, Niche type",
    "pumpsspa":"Pumps, spa",
    "pentairaosmithcommercialpumpmotors":"Pump Motors, Pumps",
    "timersswitches":"Timers Switches, Maintenance",
    "pentairrainbowleaftrapmodel180":"Leaf Traps, Accessories, Cleaner",
    "pentairstariteswimquipbronzeslidevalve":"Filter Valves, Valves, Push Pull",
    "miscellaneouswhitegoodsflowfittings":"Miscellaneous, White Goods, Flow Fittings",
    "startingplatforms":"Starting Platforms, Deck Accessories",
    "pentairstaritesunbursthalogenlight":"Lights, Lighting, Niche type",
    "pentairintellipropumpmodelvs3050":"Pumps",
    "fiberoptics":"Fiber Optics, Lighting",
    "miscellaneouslightsautocontrollers":"Miscellaneous, Lights Auto Controllers, Lighting",
    "pentairplasticfullsizeandsmallniches":"Light Niches, Lighting",
    "compoolpentairpoolcontrolsystemvalveactuators":"Valve Actuators, Automation",
    "pentairstaritesunglowlight":"Lights, Lighting, Niche type",
    "filters":"Filters",
    "pentairstaritepoolsharkmodelsgw7500gw7700":"Cleaners, Suction",
    "decorativeconcretepoolcoatings": "Deck Accessories"
}
