SHOPIFY_TEMPLATE = {
    "Handle": "",
    "Title": "",
    "Body(HTML)": "",
    "Vendor": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Google Product Category": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / AdWords Grouping": "",
    "Google Shopping / AdWords Labels": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
}

REACTION_TEMPLATE = {
    "_id": "",
    "vendor": "",
    "title": "",
    "pageTitle": "",
    "description": "",
    "metaDescription": "",
    "isVisible": True,
    "requiresShipping": True,
    "hashtags": [],
    "metafields": [{
            "key": "Original Manufacturer",
            "value": None
        },{
            "key": "Made In",
            "value": "USA"
        }
    ],
    "variants": [{
        "_id": "",
        "price": "",
        "barcode": "",
        "title": "",
        "sku": "",
        "taxable": True,
        "inventoryQuantity": 10,
        "fulfillmentService": "All Pool Spa",
        "inventoryManagement": True,
        "inventoryPolicy": True,
        "lowInventoryWarningThreshold": 1,
        "weight": 35,
        "optionTitle": "",
        "metafields": [{
                "key": "Original Manufacturer",
                "value": None
            },{
                "key": "OEM",
                "value": None
            },{
                "key": "Made In",
                "value": "USA"
            },{
                "key": "Condition",
                "value": "New"
            }
        ],
    }]
}

APS_TEMPLATE = {
    "sku":"",
    "part_number":"",
    "oem":"",
    "title":"",
    "description":"",
    "type":"",
    "category":"",
    "subcategory":"",
    "product_type": "",
    "pool_type": "",
    "pool_or_spa": "",
    "product_handle": "",
    "manufacturer":"",
    "cost":"",
    "list_price":"",
    "available":"",
    "obsolete":"",
    "discontinued": "",
    "weight":"",
    "height":"",
    "length":"",
    "width":"",
    "uom":"",
    "upc": "",
    "parent":"",
    "parent_id": "",
    "image_url":"",
    "carecraft_cost":"",
    "scp_cost":"",
    "scp_category":"",
    "scp_sku":"",
    "optimus_cost":"",
    "optimus_sku":"",
    "optimus_category":""
}
